

;     PROGRAMA PRINCIPAL
;++++++++++++ CONTROL ES R20
; CONTROL LINEA 0 SE UTILIZA EN RUTINA COMPARA
; CONTROL LINEA 1 SE UTILIZA EN LA TRANSMISION POR RADIO, INTERRUPCION TIMER2_OVF
; CONTROL LINEA 2 VERANO Ó INVIERNO A 1 INVIERNO
; CONTROL LINEA 3 MAXIMA PRODUCION SE ACTIVA EN RUTINA TECLADO ACTUA EN RUTINA RELOJ
; CONTROL LINEA 4 SONDA DE Ph PRESENTE
; CONTROL LINEA 5 CICLO PARA VERIFICAR UNA VEZ POR SEGUNDO
; CONTROL LINEA 6 SONDA DE REDOX PRESENTE
; CONTROL LINEA 7 SONDA CLORO LIBRE PRESENTE
; ++++++++++ CONTROL_1 ES R11
; CONTROL_1 LINEA 0 SE ACTIBA UNA VEZ POR SEGUNDO
; CONTROL_1 LINEA 1 OPCION UTILIZAR ACIDO Ó SOSA
; CONTROL_1 LINEA 2 PARA ANULAR LA MEDICION DE CLORO Y REDOX LA ANULA ESTANDO A UNO
; CONTROL_1 LINEA 3 PARA ACTIVAR LA OPCION DE CALCULAR EL PORCENTAJE DE PRODUCION
; CONTROL_1 LINEA 4 FUENTE 
; CONTROL_1 LINEA 5 MUESTRA SAL A AÑADIR
; CONTROL_1 LINEA 6 EQUIPO CON SENSOR DE FLUJO
; CONTROL_1 LINEA 7 SE ACTIVA CON LA PRIMERA INVERSION SE USA RUTINA APOYA DE RD Y CL

; CONTROL_2


;   CONTROL DE LOS LED
;	0	FUNCIONAMIENTO DE LA FUENTE
;	1	VERANO INVIERNO
;	2	INTERMITENTE
;	3	TIEMPO MUERTO
;	4	LED DE PH
;	5	NIVEL DE ACIDO BAJO NO ESTA PRESENTE EN LA PANTALLA
;	6	LUZ PANTALLA
;	7	POLARIDAD


; SITUACION DE LOS MENSAJES EN RAM
	.equ		PILA						=0X10FF				; PARA EL REGISTRO DE INTERRUPCIONES EN RAM
	.equ		LIN1						=0x100				; LINEA 1 DE LA PANTALLA EN RAM
	.equ		LIN2						=0X114				; LINEA 2 DE LA PANTALLA EN RAM
	.equ		LIN3						=0x0A0				; LINEA PARA TRANSMITIR EN LA UART
	.equ		L_HORAS 					=0x120				; LINEA 1 DE LA PANTALLA EN RAM PRESENTACION DE LAS HORAS
	.equ		LIN_2P						=0x1E0				; LINEA 2 DE PROGRAMACION DE MOMENTO "SIMULACION"
	.equ		PRUEBA_2					=0x220				; TEXTO
	.equ		PRUEBA_3					=0x230				; NO SE PUEDE USAR AQUI ESTA DEFINODA EN PARAMETROS
	.equ		PHP				=0X45C							; LINEA 3 CON SONDA PH
	.equ		PRUEBA_1		=0x560;			=0x240				; ES LA LINEA 4 EN RAM
	.equ		PRUEBA			=0x574;			=0x250				; ES LA LINEA 3 EN RAM
	.equ		POR_PRO			=0x588;			=0x260				; PRODUCION % 
	.equ		LIN_2S			=0x59C;			=0x270				; TEXTO " EQUIPO DETENIDO "
	.equ		A_SAL			=0X5B0;			=0x280				; TEXTO "  -.- gr/litro "
	.equ		LIN_REJILLA		=0X5C4;			=0x290				; TEXTO "  AÑADIR SAL   "
	.equ		LIN_1P			=0X5D8;			=0x2A0				; LINEA 1 DE PROGRAMACION " AJUSTE"
	.equ		LIN_CA			=0X5EC;			=0X2B0				; TEXTO  "SIN CAUDAL "
	.equ		E_REMOTO		=0X600;			=0x2C0				; TEXTO " EQUIPO REMOTO "
	.equ		E_MARCHA		=0X614;			=0x2D0				; TEXTO " EN MARCHA "
	.equ		E_PROD			=0X628;			=0x2E0				; TEXTO " SIN PRODUCCION "
	.equ		N_DEPOSITO		=0X63C;			=0x2F0				; TEXTO " NIVEL DEPOSITO "
	.equ		LIN4			=0X650;			=0x300				; LINEA PRESENTACION DE LA TEMPERATURA
	.equ		SENSOR_CAUDAL	=0X678
	.equ		LIN1P			=0X7E0;			=0x310				; LINEA PRIMERA PRESENTACION  "TIPO DE EQUIPO" ==================0x7e0 codigo nextion
	.equ		LIN2P			=0X7F4;			=0x320				; LINEA SEGUNDA PRESENTACION  " TEAP Ó DISTRIBUIDOR"
	.equ		EN_ESPERA		=0X68C;			=0x330				; TEXTO "EN ESPERA"
	.equ		N_SEG			=0X6A0;			=0x340				; PRESENTA LOS SEGUNDOS QUE FALTAN EN ERROR
	.equ		C_MANUAL		=0X6B4;			=0x350				; TEXTO " CONSULTAR MANUAL"
	.equ		AVERIA			=0X6C8;			=0x360				; TEXTO "  A V E R I A   "
	.equ		F_PRO			=0X6DC;			=0x370				; TEXTO "FALLO PRODUCCION"
	.equ		SUST_SONDA						=0x380				; TEXTO " SUSTITUIR SONDA"
	.equ		F_CONEX			=0X704;			=0x390				; TEXTO "ERROR CONEXION"
	.equ		L_BLANCA		=0X718;			=0x3A0				; LINEA "VFu Vsa Pcl Tem " 
	.equ		L_VOLTIOS		=0X72C;			=0x3B0				; VALORES DE LAS TENSIONES
	.equ		PRO_CLORO		=0X740;			=0X3C0				; PRESENTA LA PRODUCION DE CLORO EN EL REMOTO
	.equ		PRE_DES						=0X45C
	.equ		RETARDO_PRO		=0x754								; PRESENTA RETARDO DE PRODUCION AL INICIO MODO VALENCIA
	.equ        CONEX_ELECT		=0X768
	.equ		VER_SAL			=0X77C
	.equ		VIDA_ELECT		=0X790								; MIDE Y COLOCA EN RAM EL DESGASTE DEL ELECTRODO
	.equ		SCR_LIN			=0X7A4
	.equ		SAL_AGUA		=0X7B8								; SAL EN EL AGUA
	.equ		BORRAR_LINEA	=0X7A4								; LINEA EN BLANCO
	.equ		CAL_SAL			=0X8F8
	.equ		CAL_PH			=0X90C
	.equ		CAL_RD			=0X920
	.equ		CAL_CL			=0X934
	.equ		AJ_PRO			=0X948
	.equ		AJ_PH			=0X95C
	.equ		AJ_RD			=0X970
	.equ		AJ_CL			=0X984
	.equ		AJ_POL			=0X998
	.equ		AUT_RD			=0X9AC
	.equ		AUT_CL			=0X9C0
	.equ		USO_EQUIPO		=0X9D4
	.equ		LIN1G			=0X4E8								; DATOS PARA LA PANTALLA GRAFICA
	.equ		LIN2G			=0X4FC								; DATOS PARA LA PANTALLA GRAFICA	
	.equ		RG_232			=0XC01	; 0XB01 Y 0XB02				; DATOS RECIBIDOS DE LA RS232 TRES
																	; # POSICION ACCION


	.equ		ESPERA_ERROR	=0XB03					; POSICION 37  0-1
	.equ		FLUJO			=0XB04					; POSICION 39  0-1
	.equ		APOYO_CL		=0XB05					; POSICION 40  0-1
	.equ		BAJO_SAL		=0XB06					; POSICION 42  0-1
	.equ		ERROR_ELECTRODO	=0XB07					; POSICION 43  0-1
	.equ		AVERIA_FUENTE	=0XB08					; POSICION 44  0-1
	.equ		AVERIA_CPU		=0XB09					; POSICION 45  0-1		
	.equ		S_FLUJO			=0XB0A					; TIENE SONDA DE CAUDAL UN 1
	.equ		S_FUENTE		=0XB0B					; GRABA LA TENSION DE LA FUENTE
	.equ		CHECKSUM		=0XB0C
	.equ		SAL_UART		=0XB0D					; PARA MOSTRAR LA SAL EN UART
.equ		DA_ASCI 			=0xAC4					; SOLO PARA AJUSTE PRESENTA LOS VALORES RECIBIDOS POR ACI DE LA NEXTION


									; PRESENTA LAS HORAS DE USO DEL EQUIPO

.DSEG											; DIRECION INICIAL DE LA PILA EN MEMORIA RAMM
.ORG			PILA							; POSICION EN RAM 0x16F DEFINIDO EN LINEA 11 DE ESTE FICHERO 
.CSEG											; GRABAR EL PROGRAMA EN LA FLASH
.ORG			0x0000							; DIRECCION DE INICIO PROGRAMA POSICION DE MEMORIA 0X0000							; 


 
 
   	RJMP		RESET							; 00 	External Pin, Power-on Reset, Brown-out
	NOP											; 01
	RJMP		INT_0							; 02 	INTERRUPCION EXTERNA 0	
	NOP											; 03
	RJMP		INT_1							; 04	INTERRUPCION EXTERNA 1
	NOP											; 05
	RJMP		INT_2							; 06	INTERRUPCION EXTERNA 2
	NOP											; 07
	RJMP		INT_3							; 08 	INTERRUPCION EXTERNA 3	
	NOP											; 09
	RJMP		INT_4							; 0A	INTERRUPCION EXTERNA 4
	NOP											; 0B
	RJMP		INT_5							; 0C	INTERRUPCION EXTERNA 5
	NOP											; 0D
	RJMP		INT_6							; 0E 	INTERRUPCION EXTERNA 6	
	NOP											; 0F
	RJMP		INT_7							; 10	INTERRUPCION EXTERNA 7
	NOP											; 11
	RJMP		TIMER2_COM						; 12	CONTADOR 2
	NOP											; 13
	RJMP		TIMER2_OVF						; 14	Timer/Counter2 Overflow
	NOP											; 15
	RJMP		TIMER1_CAPT						; 16	Timer/Counter1 Capture Event
	NOP											; 17	
	RJMP		TIMER1_COMPA					; 18	Timer/Counter1 Compare Match A
	NOP											; 19
	RJMP		TIMER1_COMPB					; 1A	Timer/Counter1 Compare Match B
	NOP											; 1B	
	RJMP		TIMER1_OVF						; 1C	Timer/Counter1 Overflow
	NOP											; 1D
	RJMP		TIMER0_COMP						; 1E	Timer/Counter0 COMP
	NOP											; 1F
	RJMP		TIMER0_OVF						; 20	Timer/Counter0 Overflow
	NOP											; 21
	RJMP		SPI_STC							; 22	Serial Transfer Complete
	NOP											; 23
	RJMP		USART0_RX						; 24	USAR RX COMPLETADA
	NOP											; 25
	RJMP		USART0_UDRE						; 26	USAR DATO EN REGISTRO COMPLETADO
	NOP											; 27
	RJMP		USART0_TX						; 28	USAR TX COMPLETADO
	NOP											; 29
	RJMP		ADC_ADC							; 2A	ADC Conversion Completa
	NOP											; 2B
	RJMP		EE_READY						; 2C	EEPROM LEIDA LISTA
	NOP											; 2D
	RJMP		ANALOG_COMP						; 2E	COMPARADOR ANALOGICO
	NOP											; 2F	
	RJMP		TIMER1_COMPC					; 30	TIMER 1 
	NOP											; 31	
	RJMP		TIMER3_CAPT						; 32	TIMER 3 COMPC
	NOP											; 33	
	RJMP		TIMER3_COMPA					; 34	TIMER 3 COMPA
	NOP											; 35	
	RJMP		TIMER3_COMPB					; 36	TIMER 3 COMPB
	NOP											; 37	
	RJMP		TIMER3_COMPC					; 38	TIMER 3 COMPC
	NOP											; 39
	RJMP		TIMER3_OVF						; 3A	TIMER3 OVERFLOW
	NOP											; 3B										
	RJMP		USART1_RX						; 3C	USART1 RX COMPLETADO
	NOP											; 3D										
	RJMP		USART1_UDRE						; 3E	USART1 RX COMPLETADO	RJMP		USART1_RX						; 3C	USART1 RX COMPLETADO
	NOP											; 3F
	RJMP		USART1_TX						; 40
	NOP											; 41
	RJMP		TWI								; 42	INTERFACE SERIE
	NOP											; 43
	RJMP		SPM_RDY							; 44	Store Program Memory Ready

.INCLUDE "AJUSTE_PRESENTACION.ASM"
.INCLUDE "PARAMETROS_I2C.ASM"
.INCLUDE "M64DEF.INC"			; DEFINICION DE REGISTROS
.INCLUDE "PARAMETROS.ASM"		; VALORES ESPECIFICOS
;.INCLUDE "I2CP.ASM"    			; esta opcion es con i2c programado
.INCLUDE "ADC.ASM"
.INCLUDE "ini_pan.asm"
.INCLUDE "INI_PANTALLA_2.ASM"
.INCLUDE "RELOJ.ASM"
.INCLUDE "LINEA_PH.ASM"
.INCLUDE "LEC_TEC.ASM"
.INCLUDE "ENV_DOI.ASM"			; ENVIO A PANTALLA 1
.INCLUDE "ENV_DOI_2.ASM"		; ENVIO A PANTALLA 2
.INCLUDE "EEPROMRW.ASM"
.INCLUDE "CON_ADC.ASM"
.INCLUDE "COMPARA.ASM"
.INCLUDE "CALIBRARSAL.ASM"
.INCLUDE "CALIBRAR_PH.ASM"
;.INCLUDE "CALIBRACION_CL.ASM"
.INCLUDE "PCF8591.ASM"


INT_0:
	RETI
INT_1:
	RETI
INT_2:
	RETI
INT_3:
	RETI
INT_4:
	RETI
INT_5:
	RETI
INT_6:
	RETI
INT_7:
	RETI
TIMER2_COM:
	RETI
TIMER2_OVF:
	RETI
TIMER1_CAPT:
	RETI
TIMER1_COMPA:
	IN				R10,SREG
	PUSH			R10
	PUSH			R17
	LDI				R17, 00
	OUT				TCNT1L,R17		
	OUT				TCNT1H,R17
	INC				temp_tec
	INC				LEC_REL				; INCREMENTA LOS SEGUNDOS DEL RELOJ
	SET									; PONE A 1 EL REGISTRO T DE SREG
	BLD				CONTROL_1,0			; LINEA DE CONTROL 5 ACTIVADA UNA VEZ POR SEGUNDO
	POP				R17
	POP				R10
	OUT				SREG,R10
	RETI
TIMER1_COMPB:
	RET
TIMER1_OVF:
	RET
TIMER0_COMP:
	RETI
TIMER0_OVF:
	IN				R10,SREG
	PUSH			R10
	INC				R22
	POP				R10
	OUT				SREG,R10
	RETI
SPI_STC:
	RETI
USART0_RX:
	CALL			BIT_REC_0
	RETI
USART0_UDRE:
	RETI
USART0_TX:
	RETI
ADC_ADC:
	RETI
EE_READY:
	RETI
ANALOG_COMP:
;	SBI 			PORTE,7
;	CLR				R16					; APAGA LED 0 FUENTE ENCENDIDA
;	MOV				VAL_LED,R16	
;	CALL			LEDPANT
;	CALL			APAGAR_FUENTE
;	ldi				r16,(1<<SE)       ; ACTIVAR SLEEP 
;	out				MCUCR, r16
;	SLEEP

	RETI
TIMER1_COMPC:
	RETI
TIMER3_CAPT:
	RETI
TIMER3_COMPA:

	RETI
TIMER3_COMPB:
	RETI
TIMER3_COMPC:
	RETI
TIMER3_OVF:
	RETI
USART1_RX:
	CALL			BIT_REC_1
	RETI
USART1_UDRE:		; RUTINA RECIBE UN DATO TECLA PULSADA
	RETI
USART1_TX:
	RETI
TWI:
	RETI
SPM_RDY:
	RETI


RESET:

	LDI				R16,HIGH (PILA)		; Coloca en el start point de 16 bits la 
	OUT				SPH,R16 			; direcion de inicio para las interrupciones
	LDI				R17,LOW (PILA)		; y uso de las instruciones PUHS y POP      
	OUT				SPL,R17 



;*********INICIALIZAR PANTALLA //////////////

	LDI   R25, 250			; CICLO DE 250 us A 4Mhz x 100 = 0,025 seg
	RCALL RETARDO
;CALL BORRA_EEPROM		; BORRA LA EEPROM INTERNA DEL MICRO

	CALL			INI_ATMEGA64 		; INICIALIZAR PARAMETROS
;call PRU1		; RUTINA PARA ESCRIBIR EN FLASH
CLR R11
;*********************** RETARDO ERROR  PANTALLA **********************


	SER				R16
	MOV				VAL_LED,R16
	RCALL			LEDPANT
	RCALL 			INI_PANTALLA		; LLAMA A LA RUTINA PARA INICIAR LA PANTALLA
	RCALL			INI_PANTALLA_2		; INICIALIZA PANTALLA2
	RCALL			INI_PANTALLA1		; RUTINA PRESENTACION DE DATOS
	CALL			INI_LCD_2			; CARGO EL TEXTO DE LA PANTALL 2
;JMP			BIT_REC
;CALL		BIT_REC_1				; RECIBE 3 BITS
	CALL			DES_ELECTRODO		; CALCULA EL DESGASTE DEL ELECTRODO
	LDI   			LEC_REL,00			; PONE A CERO EL CONTADOR DEL RELOJ	


RET1:
	CPI	  			LEC_REL,2			; VALOR DEL TIEMPO DE RATARDO PRESENTACION
	BRLO  			RET1				; COMPRUEBA EL TIEMPO DE RETARDO SI ES MENOR DE 2 A RET1
	LDI   			YH,high(LIN_2S)		; direccion alta del TEXTO en Ram
	LDI   			YL,low (LIN_2S)		; direccion baja del TEXTO en Ram 
;	RCALL			UART_INI
	LDI				LEC_REL,50			; VALOR INICIAL RETARDO DE ENCENDIDO
	LDI				R25,51				;Valor para configurar 9600BPS A 8MH de la UART 51para 11.059 71
	LDI				CONTROL,0
; PARAMETROS INICIALES LECTURA DEL PORCENTAJE DE PRODUCION EN CASO DE CUBIERTA CERRADA
	LDI 			R17,RE_PRO
	CALL			EEPROM_RW
	STS				RAM_PRO_PRO,R18
; ACTIVACION DE LA BOMBA DE APOYO PARA CLORO Y REDOX
	LDI				R17,apoyo_rd_cl	; POSICION EN EEPROM
	RCALL			EEPROM_RW			; RUTINA DE LECTURA DE EPROM
	CPI				R18,9				; COMPARA CON 9
	BRLO			RD_CL1				; SI ES MENOR VA A RD_CL1
	LDI				R18,8
	RCALL			EEPROM_ES			; ACTUALIZA LA EEPROM CON 4
RD_CL1:
	STS				ram_rd_cl,R18		; PASA A RAM EL VALOR

; PARAMETROS NUMERO DE CICLOS PARA LA INVERSION
 	LDI				R17, ciclos_minuto	; POSICION DEL PH PROGRAMADO EN EEPROM $000
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	CPI				R18,5				; COMPARA CON 5 SI ES MAYOR RECTIFICA EL VALOR
	BRLO			SALTA_1
	LDI				R18,4				; Y PONE 4 NUEVA ORDEN SON 2 ****************************************
	MOV				R19,R18
SALTA_1:
	STS				RAM_CICLOS,R18
	LDI				R19,48
	ADD				R19,R18
	STS				0x9AA,R19
	LDI				R17,CICLOS_MINUTO
	RCALL			EEPROM_ES			; ACTUALIZA LA EEPROM CON EL VALOR INICIAL
	LDI				R17,EE_CICLOS
	ADD				R17,R18
	CALL			EEPROM_RW
	INC				R18
	CPI				R18,200			; SI ES MAYOR DE 200 PONE EL REGISTRO A CERO
	BRBC			0,SALTA2			; Y SALTA A 2 PORA INCREMENTAR EL SEGUNDO REGISTRO
	CALL			EEPROM_ES
	RJMP			SALTA3
SALTA2:
	LDI				R18,0				; GRABA CERO 
	CALL			EEPROM_ES
	LDI				R19,16
	ADD				R17,R19
	CALL			EEPROM_RW			; LEE EL REGISTRO ALTO
	INC				R18					; Y LO INCREMENTA EN 1 UNIDAD
	CALL			EEPROM_ES			; Y LO GRABA


SALTA3:
; PARAMETROS INICIALES AJUSTADOS DEL PH
 	LDI				R17,PH_MEN			; POSICION DEL PH PROGRAMADO EN EEPROM $000
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,PH_MAX
	RCALL			COMP
	SBRC			CONTROL,0
	LDI				R18,74
	LDI				R25,PH_MIN
	RCALL			COMP
	SBRS			CONTROL,0
	LDI				R18,74				; SI SE MENOR PONE EL PH NORMAL
	LDI				R17,PH_MEN
	RCALL			EEPROM_ES			; ACTUALIZA LA EEPROM CON EL VALOR INICIAL
	STS				RAMP_PH,R18		; GRABAR EN LA MEMORIA RAM EL VALOR PROGRAMADO DEL PH $1D1

; CALIBRACION SONDA DE PH	 VALOR ENTRE 20 Y CERO INICIAL 10
	LDI				R17,PHC_MEN		; POSICION DE MEMORIA A LEER EN EEPROM $005
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,20
	RCALL			COMP				; COMPARA R18 CON R25
	SBRC			CONTROL,0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18,10
	STS				RAMC_PH,R18		; VALO CALIBRACION PH $1D2
	LDI				R17,PHC_MEN
	RCALL			EEPROM_ES			; ACTUALIZA EL VALOR INICIAL DEL PH
	LDI				R24,74				; VALOR INICIAL DE MEDICION DEL PH
	STS				RAM_PH,R24			; ALMACENA EN LA MEMORIA RAM EL PH $1D0

; PARAMETROS INICIALES AJUSTE DE LA SAL


; CALIBRACION MEDICION CONCENTRACION DE SAL	NUMERO DE MEDICIONES ENTRE 50 Y 180 EN CASO CONTRARIO PONE 100
	LDI				R17,SAC_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $006
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,210
	RCALL			COMP				; COMPARA R18 CON R25
	SBRC			CONTROL,0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18,176
	LDI				R25,50
	RCALL			COMP
	SBRS			CONTROL,0
	LDI				R18,176				; SI SE MENOR PONE EL PH NORMAL
	LDI				R17,SAC_MEN
	RCALL			EEPROM_ES			; GUARDA EN EEPROM EL VALOR INICIAL DE 100
	STS				RAMC_SAL,R18		; VALOR CALIBRACION SAL $1DD
	LDI				R24, 176			; VALOR INICIAL DE MEDICION DE LA SAL
	STS				RAM_SAL,R24			; ALMACENA EN LA MEMORIA RAM
	STS				RAM_SAL_C,R24		; ALMACENA LA MEDICION EN LA MEMORIA RAM

; PARAMETROS INICIALES DE CLORO LIBRE
	LDI				R17,CL_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $002
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,CL_MAX + 1
	RCALL			COMP
	SBRC			CONTROL,0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18,10
	LDI				R25,CL_MIN
	RCALL			COMP
	SBRS			CONTROL,0
	LDI				R18,8				; SI SE MENOR PONE EL PH NORMAL
	STS				RAM_CL,R18			; GRABAR EN LA MEMORIA RAM $1D6
	STS				RAMP_CL,R18			; GRABAR EN LA MEMORIA RAM $1D7
; COLOCA EN FORMA DE TEXTO EL VALOR DEL CLORO PROGRAMADO PARA MOSTRARLO EN LA NEXTION
	MOV				R24, R18			; PONE EL VALOR EN R24 PARA CONVERTIRLO EN DECIMAL
	RCALL			RADC   				; CONVERTIR UN NUMERO EN DIGITOS DATO EN R24
	STS				$992, R2			; PONE EL RESULTADO EN PANTALLA DECENAS DE CL
	LDI				R16, 46
	STS				$993, R16
	STS				$994, R3			; PONE EL RESULTADO EN PANTALLA UNIDADES DE CL
	WDR

; PARAMETROS INICIALES AJUSTE DE LA SONDA DE CLORO LIBRE
	LDI				R17,CLC_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $004
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,250				; VALOR MAXIMO
	RCALL			COMP
	SBRC			CONTROL,0			; VERIFICA SI ES CERO EL BIT 7 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18,200				; VALOR ESTANDAR
	LDI				R25,150				; VALOR MINIMO
	RCALL			COMP				; RUTINA COMPARACION
	SBRS			CONTROL,0
	LDI				R18,200				; SI ES MENOR PONE EL NORMAL
	STS				RAMC_CL,R18			; GRABA EL VCALOR DE CALIBRACION DEL CLORO $1D8
	WDR

; PARAMETROS INICIALES DEL REDOX programados
	LDI				R17,RD_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $003
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,RD_MAX	+ 1		; REDOX MAXIMO 170X5=850
	RCALL			COMP
	SBRC			CONTROL,0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18,128				; REDOX PREFIJADO
	LDI				R25,RD_MIN			; REDOX MINIMO
	RCALL			COMP
	SBRS			CONTROL,0
	LDI				R18,128				; REDOX PREFIJADO
	STS				RAM_RD,R18			; GRABAR EN LA MEMORIA RAM $1D9
	STS				RAMP_RD,R18			; GRABAR EN LA MEMORIA RAM $1DA
	WDR
; VALORES DE CALIBRACION DEL REDOX, 230 MEDICIONES
	LDI				R17,RDC_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $007
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,254				; VALOR MAXIMO
	RCALL			COMP
	SBRC			CONTROL,0			; VERIFICA SI ES CERO EL BIT 7 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18,237				; VALOR ESTANDAR
	LDI				R25,200				; VALOR MINIMO
	RCALL			COMP				; RUTINA COMPARACION
	SBRS			CONTROL,0
	LDI				R18,237				; SI SE MENOR PONE EL NORMAL
	STS				RAMC_RD,R18			; GRABA EL VCALOR DE CALIBRACION DEL CLORO $1DB


; parametros iniciales de la producion
	LDI				R17,PRO_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $001
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25,PRO_MAX + 1
	RCALL			COMP
	SBRC			CONTROL,0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18,90
	LDI				R25,PRO_MIN
	RCALL			COMP
	SBRS			CONTROL,0
	LDI				R18,90				; SI SE MENOR PONE EL PH NORMAL
	STS				RAM_PRO,R18			; GRABAR EN LA MEMORIA RAM $1D4
	STS				RAMP_PRO,R18		; GRABAR EN LA MEMORIA RAM $1D5
	WDR

	LDI				R24,00				; VALOR INICIAL PARA ACTIVAR EL PERRO GUARDIAN
	OUT				WDTCR,R24			; ACTIVA EL PERRO GUARDIAN
	CLR				CONTROL
	CBI				PORTD,4				; APAGA VENTILADOR Y CONTROL REMOTO
	CLR   			R16
	STS  			seg,R16				; PONE A CERO LOS SEGUNDOS
	STS   			minu,R16			; PONE A CERO LOS MINUTOS
	STS   			hora,R16			; PONE A CERO LAS HORAS
	MOV				VAL_LED,R16
	RCALL			LEDPANT
	CBI				PORTD,B_ACIDO		; APAGA BOMBA DE ACIDO
; DETECTAR EL CONTROL DE FLUJO
; SE ACTIVA HACIENDO UN PUENTE EN LA CLEMA AL ENCENDER EL EQUIPO
	LDI				R17,SENSOR_FLUJO	; LEE SI YA TIENE SENSOR DE FLUJO POSICION 09D EN EEPROM
	CALL			EEPROM_RW
	CPI				R18,$FF
	BRNE			SONDA_SI			; SI DISTINTO TIENE SONDA
	RJMP			SONDA_NO
SONDA_SI:
	CLT									; PONE A CERO EL BIT T DE SREG
	BLD				CONTROL_1,6			; PASA EL BIT T A CONTROL_1,6 SONDA DE CAUDAL PONE A CERO
	LDI				R18,1
	STS				FLUJO,R18			; PASA LA SEÑAL UN UNO A REGISTRO DE RS232 QUE ES B04 EN RAM
	RJMP			SONDA_ACT
SONDA_NO:		; COMPRUEBA SI TIENE SONDA CONECTADA
	SET									; PONE A CERO EL BIT T DE SREG
	BLD				CONTROL_1,6			; PASA EL BIT A CONTROL_1,6 ANULA SONDA SONDA DE CAUDAL
	LDI				R18,$FF
	STS				FLUJO,R18			; PASA LA SEÑAL A REGISTRO DE RS232
	SBIC			PINE,4				; SALTA LA SIGUIENTE INSTRUCCION SI ES UNO  TIENE SONDA
	RJMP			SONDA_ACT			; VA A SIN_SONDA SI ES UNO
	LDI				R17,sensor_flujo
	LDI				R18,1				; GRABA UN 1 SE ACTIVA LA SONDA DE CAUDAL 
	CALL			EEPROM_ES			; ACTIVA LA DETECCION 
	CLT			
	BLD				CONTROL_1,6			; PASA EL BIT A CONTROL_1,6 SONDA DE CAUDAL
	LDI				R18,1
	STS				FLUJO,R18			; PASA LA SEÑAL A REGISTRO DE RS232
SONDA_ACT:
; OPCION VERANO INVIERNO
	LDI				R17,VER_INV			; POSICION DE MEMORIA A LEER EN EEPROM $1DE
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	BST				R18,0				; ALMACENA EL BIT CERO EN EL REGISTRO T DE SREG
	BRTC			INVIERNO_A			; SALTA A INVIERNO SI ES CERO
	RJMP			VERANO_A
INVIERNO_A:
	LDI				R17,EE_CICLOS
	CALL			EEPROM_RW
	INC				R18
	CPI				R18,200				; SI ES MAYOR DE 200 PONE EL REGISTRO A CERO
	BRBC			0,SALTA2A			; Y SALTA A 2 PORA INCREMENTAR EL SEGUNDO REGISTRO
	CALL			EEPROM_ES
	RJMP			SALTA3A
SALTA2A:
	LDI				R18,0				; GRABA CERO 
	CALL			EEPROM_ES
	LDI				R19,16
	ADD				R17,R19
	CALL			EEPROM_RW			; LEE EL REGISTRO ALTO
	INC				R18					; Y LO INCREMENTA EN 1 UNIDAD
	CALL			EEPROM_ES			; Y LO GRABA
SALTA3A:
	MOV				R16,VAL_LED
	ORI				R16,0B00000010		; ENCIENDE LED VERANO INVIERNO
	MOV				VAL_LED,R16
	SBR				CONTROL,0B00000100	; ACTIVA LA SEÑAL DE INVIERNO EN CONTROL
VERANO_A:


; OPCION PRODUCION AUTOMATICA O ANULACION DE LA MEDICION DE CLORO Y REDOX
	LDI				R17,PA_PM
	CALL			EEPROM_RW
	BST				R18,0				; PASA EL REGISTRO 0 DE R18 A T		
	BLD				CONTROL_1,2			; PASA EL REGISTRO T DE SREG A CONTROL1_2
; POR ERROR EN EL SIMULADOR DESACTIVA LA PRESENTACION DE AÑADIR SAL
	SET									; PONE ES REGISTRO T A 0 SET LO PONE A 1
	BLD				CONTROL_1,5			; PASA EL REGISTRO T A CONTROL_1
; OPCION INICIO DE POLARIDAD
	LDI				R17,POL_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $1DE
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	STS				RAM_POL,R18
	LDI				R17,POL_MEN			; POSICION EN EEPROM DE LA POLARIDAD
	LDS				R18,RAM_POL			; VALOR POLARIDAD CICLO ANTEIOR
	INC				R18					; INCREMENTAMOS UNO			
;	RCALL			I2CE_2404			; ESCRIBE EL NUEVO VALOR EN LA EEPRON EXTERNA
	RCALL			EEPROM_ES
	BST				R18,0				; ALMACENA EL BIT MENOS IMPORTANTE DE LA MEDICION DEL POLARIDAD EN EL REGISTRO T DE SREG
	BRTC			RELE_POLARIDAD		; SI ESE BIT ES CERO 
;	BLD				VAL_LED,3			; Y LA PASA AL CONTROL DE POLARIDAD	PARA NO APAGAR EL RELE Y ACTIBAR LED
	BLD				VAL_LED,7			; ESTE ES EL LED DE SAL QUE NO VALE PA NA
	SBI				PORTD,6				; APAGA RELE POLARIDAD 1
	RJMP			REMOTO
RELE_POLARIDAD:
	SBI				PORTD,7				; APAGA RELE POLARIDAD 0

; TERMINA INICIALIZACION DEL PROCESO ********************************************************/////

; ********* PROGRAMA PRINCIPAL //////////////// AQUI PROGRAMA PRINCIPAL *************************

REMOTO:	;*******************SELECIONA LA POLARIDAD MAS EFECTIVA ************************************

	CALL			CONTROL_ELECTRODO   ;**** UTILIZA R20 QUE ES EL REGISTRO DE CONTROL PRINCIPAL NO IMPORTA
; RETARDO PARA VALENCIA 240 SEGUNDOS
LDI	R19,00
STS	0XB00,R19
STS	0XB01,R19
STS	0XB02,R19
STS	0XB03,R19
;STS	0XB04,R19	; NO BORRAR SEÑAL CON SENSOR DE FLUJO
STS	0XB05,R19
STS	0XB06,R19
STS	0XB07,R19
STS	0XB08,R19
STS	0XB09,R19

;	LDI				R17, retardo_inicio
;	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
;	CPI				R18, 1				; SI ES UNO VA A RUTINA DE RETARDO
;	BRNE			REMOTO23			; COMO ES DISTINTO VA A REMOTO23
;	CALL			RETARDO240			; RUTINA DE RETARDO240
REMOTO23:
	CBI				PORTB,S_RD_CL		; DESCONECTA EL  APOYO LA BOMBA 1
	SET
	BLD				CONTROL_1,4
	CALL			COMPARA2
	LDI				R19,00
	STS				NCICLOS,R19			; LIMPIA LA POSICION NCICLOS en ram
	STS				MINU,R19
	LDI				R19,20
	MOV				LEC_REL,R19
	SBIS			PINB,3				; VERIFICA QUE FUENTE TIENE LA 150 CON PUENTE
	SBR				CONTROL,0B00000010	; PONE A UNO EL BIT 1 SI HAY PUENTE
	CALL			MED_INI_SAL			; LEE EL VALOR INICIAL DE LA SAL PARA ELIMINAR EL ERROR
	SBIS			PINB,4				; PRINCIPAL O REMOTO salta la siguiente instrucion si es uno
	RJMP			REMOTO1				; SI HAY PUENTE REMOTO
	LDI				R18,10				; PONE EL CONTADOR DE SEGUNDOS A 10
	STS				RAM_CAUDAL,R18		; LIMPIA DE SEGUNDOS EL CONTROL DE CAUDAL ENPIEZA EN 10 SEGUNGOS
; LINEA 5 6 Y 7 DEL PUERTO B COMO SALIDA DDRB A CREO PARA ENCENDER LA FUENTE DESDE EL PRINCIPIO
	LDI				R16,0B01100110		; PUERTO 4 REMOTO Y 3 TIPO DE FUENTE COMO ENTRADA SEÑAL
	OUT   			DDRB,R16			; PUERTO 5 6 Y 7 ENTRADA DEL MESTRO
;CALL			;
;CALL			LEC2D					; PARA ACTUALIZAR HORAS TEMPERATURA Y VIDA DEL ELECTRODO
;CALL			P_NEXTION_TEAP				; ENVIA EL ANAGRAMA PEQUEÑO DE TEAP
CALL			P_NEXTION_AC			; ACTUALIZA HORAS, TEMPERATURA Y DESGASTE DEL LECTRODO
; INICIALIZA EL TIMER A USAR EN PWM
;CALL		DC_PWM_0		; ACTIVA PWM TIMER 0 ***********************************************************
;CALL		DC_PWM_2		; ACTIVA PWM TIMER 2 ***********************************************************
CALL		DC_PWM_3		; ACTIVA PWM TIMER 3 ***********************************************************

	RJMP			PRO					; NO HAY PUENTE PROGRAMA MAESTRO

										; PROGRAMA DEL EQUIPO REMOTO
REMOTO1: ;CAMBIAMOS EL TEXTO EN LA MEMORIA RAM
;   LDI   			YH,0x01        		; direcion alta donde se pone el texto en RAM
;   LDI   			YL,0xE0      		; direccion baja donde se pone el texto en RAM 
;   LDI   			ZH,high(TEXTO2*2)	; direccion alta del TEXTO en Flash
;   LDI   			ZL,low(TEXTO2*2) 	; direccion baja del TEXTO en Flash 
;   LDI   			R16,48      		; longitud de texto a copiar en RAM
;*** RURINA CARGAR TEXTO DE FLASH A RAM  
;EN Y (YH,YL) POSICION EN RAM
;EN Z (ZH,ZL) POSICION EN FLASH
;EN R16 NUMERO DE LETRAS (BYTS)
CARGATEXTO1:
;	LPM      							; leemos TEXTO de FLASH y lo almacena en R0
;	ADIW  			ZL,1   				; apuntamos al siguiente elemento 
;	ST    			Y,R0				; guardamos en RAM POSICION Y EL CONTENIDO DE R0
;	ADIW  			YL,1      			
;	DEC   			R16      			; Hemos terminado..?? 
;	BRNE  			CARGATEXTO1   		; NO...seguimos cargando 
; ELIMINADO PARA NO UTILIZAR LA PANTALLA
	LDI				R16, 128				; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2";	LDI				YH, HIGH (E_PROD)	; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YH,HIGH(AVERIA)
	LDI				YL,LOW(AVERIA)		; direccion BAJA DEL TEXTO EN RAM  " SIN PRODUCCION 
	LDI				R17,16   			; bytes a enviar 
	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO E PANTALLA
	CBI				PORTD,B_ACIDO		; APAGA BOMBA DE ACIDO
	LDI				R16,0B00000111		;PUERTO 4 REMOTO Y 3 TIPO DE FUENTE COMO ENTRADA SEÑAL
	OUT   			DDRB,R16			; PUERTO 5 6 Y 7 ENTRADA DEL MESTRO
	LDI				R16,0B11111111		;PUERTO 4 Y 3 COMO ENTRADA SEÑAL PARA EL CONTROL REMOTO		
	OUT   			PORTB,R16			; Y PUERTO 0 TIPO DE FUENTE
; CONFIGURAR PUERTO E4 COMO ENTRADA DE CONTROL MARCHA PARADA
	LDI				R16,0B00000000
	OUT				DDRE,R16
	LDI				R16,0B00010000		; PUERTO 4 ENTRADA SEÑAL ON OFF
	OUT				PORTE,R16

;	IN				R18,PINB			; VERIFICA LA CONEXION DEL CABLE DE CONTROL
;	CPI				R18,0x0F
;	BRLO			REMOTO2				; SI ES MENOR VA A REMOTO2, CABLE MAL CONESTADO
;	RJMP			CARGATEXTO1
REMOTO2:
	LDI				R16,128				; 1ª LINEA DE PANTALLA
	RCALL			ENVINT				; Y ENVIA EN MANSAJE A PANTALLA 1º INFORMACION DE LINEA Y....
	LDI				YH,HIGH(E_REMOTO) 	; TEXTO A ENVIAR A PANTALLA " EQUIPO REMOTO "
	LDI				YL,LOW(E_REMOTO) 	; TEXTO A ENVIAR A PANTALLA
	LDI				R17,20				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			;  EL TEXTO 16 CARACTERES
	RCALL			RELOJ
	RCALL			LEDPANT
;	LDS  			R19,minu			; CARGA LOS MINUTOS 
;	CPI				R19,01				; PARA ACTIVAR LA MEDICION DEL PH VARIAS VECES EN EL PRIMER MINUTO
;	BRBS			0, REMOTO2			
;	CPI				R19,100				; COMPARA CON 100 PARA NO ENCENDER LA FUENTE Y PODER INVERTIR LA POLARIDAD
;	BRBC			0, REMOTO2			; SI ES MAYOR NO MIDE NI REDOS NI CLORO SALTA A REMOTO2 y para la fuente
;	RCALL			PRO4				; MEDICION CLORO LIBRE-- ES LA LINEA DE CONTROL REMOTO
;	CALL			PRO_CONTROL			; CONTROL MEDIENTE CABLE PLANO COMO REMOTO
	SBIS			PINE,4				; AQUI VERIFICA SI ESTA EN MARCHA O PARADO
	RJMP			REMOTO2A
	LDI				R16,192				; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2"
	LDI				YH,HIGH(E_MARCHA)	; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL,LOW(E_MARCHA)	; direccion BAJA DEL TEXTO EN RAM  " EN MARCHA "    	
	CALL			ENCENDER_FUENTE
	RJMP			REMOTO2B
REMOTO2A:
	LDI				R16,192				; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2"
	LDI				YH,HIGH(E_PROD)		; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL,LOW(E_PROD)		; direccion BAJA DEL TEXTO EN RAM  " SIN PRODUCCION "    	
	CALL			APAGAR_FUENTE
REMOTO2B:
 	LDI				R17,20   			; bytes a enviar 
	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO E PANTALLA
	RJMP			REMOTO2

; LEE LOS AMPERIOS O PRODUCION DE CLORO  "ESTO ESTA ANULADO
;	LDI				R18,P_TCL			; LEE LOS AMPERIOS
;	LDI				R26,110				; NUMERO DE LECTURAS AMPERIOS
;	CALL			ADC_P
;	CPI				R24,4				; MENOS DE 2 PONE UN CERO
;	BRLO			REMOTOB_1
;	RJMP			REMOTOB_2
;REMOTOB_1:
;	LDI				R24,00				; PONE UN CERO
;;REMOTOB_2:
;	LSR				R24
;	CALL			RADC
;	STS				$74B,R2				; PARA PANTALLA 20X4
;	STS				$74C,R3				; PARA PANTALLA 20X4
;	LDI				R16,214				; 11000000 escribir en linea 4, linea 2 ES (192)( linea 4 seria 212)
;	RCALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2"
;	LDI				YH,HIGH(PRO_CLORO)		; POSICION ALTA DEL TAXTO EN RAM 080
;	LDI				YL,LOW(PRO_CLORO)		; direccion BAJA DEL TEXTO EN RAM  " SIN PRODUCCION "    
;	LDI				R17,20   			; bytes a enviar 
;	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO E PANTALLA
;	RJMP			REMOTO2				; SALTA A REMORO2
							


PRO: ; PROGRAMA PRINCIPAL MASTER
;CALL		DC_PWM_0		; ACTIVA PWM TIMER 0 ***********************************************************
;CALL		DC_PWM_2		; ACTIVA PWM TIMER 2 ***********************************************************

	SET
	BLD				VAL_LED,3			; COPIA T DE SREG EN REGISTRO 2 DE LOS LED ES INTERMITENTE
	RCALL			LEDPANT
	WDR
	SBRS			CONTROL_1,0			; SALTA LA PROXIMA INSTRUCION SI ES UNO,
	RJMP			PRO
CALL		DC_PWM_0A		; ACTIVA PWM TIMER  ***********************************************************
;CALL		SERVO			; CONTROLA UN SERVO CON POT DE Ph
;CALL		MOTOR_PAP
	CALL			UART_INI0			; INICIALIZA PUERTO SERIE 0

;	CALL			UART_INI1			; INICIALIZA PUERTO SERIE 1
	CALL			INI_NEXTION_P		; NEXTION PANTALLA PRINCIPAL 
;SBRS			LEC_REL,0			; PARA ENVIAR DATOS CADA DOS SEGUDOS	
;	CALL			CADENA_UART			; ENVIAR DATOS AL LOLIN *********************************
	CLT									; PONE A CERO EL BIT T DE SREG
	BLD				VAL_LED,3			; COPIA T DE SREG EN REGISTRO 2 DE LOS LED ES INTERMITENTE
	BLD				CONTROL_1, 0		; PASA EL REGISTRO T A CONTROL_1
	RCALL			LEDPANT
	RCALL			TECLADO				; LEER TECLADO


PRO_1: ; LA CONFIGURACION DE LAS LINEAS EN LA RUTINA "LINEA_PH"

; FRECUENCIA MEDICION DE PH
	CALL			LINEA3
 	RCALL			PRO2				; ESTA RUTINA PARA MEDIR Y CONTROLAR EL PH
 	SBRS			CONTROL,4			; COMPRUEBA QUE TIENE SONDA DE PH
	RJMP			PROA3 				; SI NO TIENE VA A...
; COMPRUEBA QUE TIENE SONDA DE CLORO LIBRE
	SBRC			CONTROL, 7 			; COMPRUEBA SI TIENE SONDA DE CLORO LIBRE
	RJMP			PRO3A_CL			; SI TIENE SALTA A 
	SBRC			CONTROL,6			; COMPRUEBA SI TIENE SONDA DE REDOX
	RJMP			PRO3A_RD			; SI TIENE SALTA A 
; COMO NO TIENE SONDAS PRESENTA PH Y PRODUCCION


; PANTALLA CON SONDA DE PH Y SIN REDOX NO CLORO

; RUTINA PARA 


	LDI				R19,192
	RCALL			LINEA1 				; LINEA2 CON SONDA DE PH LINEA 1 "pHp -.- pH agua -.-"
	LDI				R19,148
	RCALL			LINEA1PH			; CON SONDA DE PH LINEA 3 "PRODUCION 90 %" RUTINA LINEA_PH
	LDI				R19,212
	RCALL			LINEA2PH			; LINEA 4 "SAL EN AGUA" O AÑADIR SAL
	RCALL			ANADIR_SAL			; MUESTRA AÑADIR SAL SI ES NECESARIO
	RJMP			PROA4			

PROA3:		; PANTALLA SIN SONDA DE PH
	LDI				R16, 148			; BORRAR LINEA 3
	CALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2"
	LDI				YH,HIGH(BORRAR_LINEA)	; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL,LOW (BORRAR_LINEA)	; direccion BAJA DEL TEXTO EN RAM  "CONSULTAR MANUAL"    	
  	LDI				R17,20   			; bytes a enviar 
	CALL			ENVIARTEXTO			

	LDI				R19,212				; VALOR DE LA LINEA A ESCRIBIR
	RCALL			LINEA2PH			; MOSTRAR SAL EN EL AGUA 
	RCALL			ANADIR_SAL			; MUESTRA LA SAL A AÑADIR SI ES NECESARIO LINEA 4
	LDI				R19,192
	RCALL			LINEA1PH			; Mostrar linea 1 solo % de produccion
			; LINEA 4 MUESTRA SAL A AÑADIR EN CASO DE SER MENOR DE 5
	RJMP			PROA4
PRO3A_CL: ; PANTALLA CON CLORO

;       20x4        16x4   tipo de display
; linea 1-128 		128 
; linea 2-192		192
; linea 3-148		144
; linea 4-212		208
	LDI				R19,192
	RCALL			LINEA1 				; LINEA2 CON SONDA DE PH LINEA 1 "pHp -.- pH agua -.-"
	LDI				R19,148
	RCALL			LIN_AUTO_CL			; LINEA 3 "PROD. AUTO CL -.- PPM"
	LDI				R19,212
	RCALL			LINEA2PH			; LINEA 4 "SAL EN AGUA" O AÑADIR SAL
	RCALL			ANADIR_SAL			; MUESTRA LA SAL A AÑADIR SI ES NECESARIO LINEA 4	
	RJMP 			PROA4

PRO3A_RD:	; PANTALLA CON REDOX
	LDI				R19,192
	RCALL			LINEA1 				; LINEA 2 "pHp -.- pH agua -.-"
	LDI				R19,148
	RCALL			LIN_AUTO_RD			; LINEA 3 "PROD. AUTO RDX ---mV"
	LDI				R19,212
	RCALL			LINEA2PH			; LINEA 4 "SAL EN AGUA" O AÑADIR SAL
	RCALL			ANADIR_SAL			; MUESTRA LA SAL A AÑADIR SI ES NECESARIO LINEA 4
;RCALL  BORRAR_PANTALLA

; FRECUENCIA MEDICION DE TEMPERATURA y SAL SOLO CON FUENTE ENCENDIDA

PROA4:
	CALL			VOLTIOS				; RUTINA QUE MIDE LAS VOLTIOS Y LAS PASA A P GRAFICA YMIDE AMPERIOS
	SBIS			PIND,4				; SI LA FUENTE ESTA APAGADA SALTA A
	RJMP			PROA				; PROA PARA NO MEDIR LA SAL
	LDS				R19,MINU
	CPI				R19,1				; RETARDO PARA MEDIR LA SAL DEL 3%
	BRLO			PROA
;LDS		R19,SEG
;CPI	R19,4
;BRLO PROA
	RCALL			PRO3				; RUTINA MEDICION DE SAL
	RCALL			ADC_P3				; CONVIERTE EL VALOR LEIDO A PANTALLA 

; MEDICCION DE LA TEMPERATURA
;	LDI				R19,0				; DIRECIONAMIENTO DEL PERIFERICO
	LDI				R18,P_TEMP			; LINEA A LEER
	LDI				R26,80				; NUMERO DE LECTURAS
	CALL			ADC_P
PROA4A:
;LDI R24,00
	STS				RAM_TEMP,R24		; GUARDA LA LECTURA EN LA MEMORIA RAM
	CALL			PCF2_T				; RUTINA QUE PREPARA LA PRESENTACION DE LA TEMPERATURA
	NOP

PROA:  
	RCALL			RELOJ
	RCALL			TECLADO
;CALL LIN_PGRAFICA						; PONE LA INFORMACION EN LA PANTALLA GRAFICA
	WDR
	NOP


; PARA MEDIR EL CLORO O REDOX LO MIDE DESPUES DE 30 SEGUNDOS
	WDR
	LDS  			R19,minu			; CARGA LOS MINUTOS 
	CPI				R19,100				; COMPARA CON 100 PARA NO ENCENDER LA FUENTE Y PODER INVERTIR LA POLARIDAD
	BRBC			0,PRO1B				; SI ES MAYOR NO MIDE NI REDOS NI CLORO SALTA A PRO1B y para la fuente
	CPI				R19,1				; NO ENCIENDE LS FUENTE
	BRBS			0,PRO1A
;	SBRS			CONTROL_1,2			; SALTA LA PROXIMA INSTRUCION SI ES UNO MIDE CLORO Y REDOX, OPCION NORMAL
;	RJMP			PRO1A				; APAGA EL CIRCUITO DE APOYO Y NO MIDE MAS
	RCALL			PRO4				; MEDICION CLORO LIBRE
	SBRC			CONTROL,7 			; COMPRUEBA SI TIENE SONDA DE CLORO LIBRE
	RJMP			PRO1A				; SI TIENE SALTA A PRO1A
	RCALL			PRO5				; MEDICION REDOX
	WDR
PRO1A:
	RJMP			PRO					; COMIENZA EL CICLO DEL PROGRAMA PRINCIPAL	

PRO1B: ; RUTINA PARA CUANDO EL TIEMPO ES SUPERIOR A 100	 APAGA LA FUENTE  
	RCALL			TECLADO				; LEER TACLADO	
	CALL			APAGAR_FUENTE
	RJMP			PRO
;+++++++++ TERMINA PROGRAMA PRINCIPAL +++++++++++++++++

;*** RUTINA PARA CONTROLAR LOS LED DE LA PANTALLA Y LA LUZ
LEDPANT:
	OUT				PORTA,val_led		; r15 registro control led pantalla
	CBI				PORTC,led_pant		; pone a 0 el bit de grabacion del 74lh374 
	NOP
	NOP
	SBI				PORTC,led_pant		; pone a 1 , graba el valor de portA en el 74LH374, enciende los led
	NOP
	NOP
	RET

;*** RUTINA PARA ENVIAR TEXTO A PANTALLA EN R17 NUMERO DE LETRAS
;    EN Y LA POSICION EN MEMORIA RAM ( YH, YL )	PRECISA RUTINA ENVIARBYTE
ENVIARTEXTO: 
	LD				r16, Y+      		; carga byte en r0 e incrementa Y
	RCALL			ENVIARBYTE  		; lo enviamos 
	DEC				r17 				; descuenta uno
	BRNE			ENVIARTEXTO   		; si quedan mas seguimos enviando 
	RET


;***********RETARDO DE 22 uS*********** 
; el retardo es : 195uS de retardo para r25=250 y 4Mhz de frecuencia
;  PARA 4MZ SOLO UNA INSTRUCION NOP PARA 8MZ 6 INSTRUCIONES NOP

RETARDO:
	WDR
	NOP
	NOP
	NOP
	NOP
	NOP
	DEC				R25 
	BRNE			RETARDO   		;
	RET

; RUTINA PARA CARGAR LOS VALORES PROGRAMADOS EN EEPROM A RAM
; CARGA EL PH


LINEA1: ;RUTINA ESCRITURA LINEA2 CON PH 
	LDI				R16,192				; ESCRIBIR LINEA 2
	RCALL			ENVINT				; En subrrutina Env_doi Envia instrucion para escribir en linea 1
	LDI				YH, HIGH(PHP)		; POSICION BIT ALTO DEL TEXTO A ENVIAR ram en 070
	LDI				YL, LOW(PHP)		; POSICION BIT BAJO DEL TEXTO A ENVIAR
	LDI				R17,20				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			; RUTINA EN ESTE FICHERO PRECISA SUBRRUTINA ENV_DOI	
	RET	


	STS				$10F,R16
	STS				$111,R16	
	SBRC			CONTROL,7 			; COMPRUEBA SI TIENE SONDA DE CLORO LIBRE
	RJMP			LINEA1A
	SBRC			CONTROL,6			; COMPRUEBA SI TIENE SONDA DE REDOX
	RJMP			LINEA1A
	LDS				R24,RAMP_PRO
;	SBRC			CONTROL_1,3
;	LDS				R24,RAM_PRO_PRO_M	; SOLO EN CASO DE ACTUAR EL PORCENTAJE DE PRODUCION
	SBRC			CONTROL,3			; SALTA LA PROXIMA INSTRUCION SI ES CERO, SUPERCLORACION
	LDI				R24,100				; SOLO EN CASO DE SUPERCLORACION
	RCALL			RADC				; RUTINA PARA CONVERTIR EN ANALOGICO

	STS				$106,R1
	STS				$107,R2
	STS				$108,R3
	LDI				R16,37				; PONE UN %
	STS				$109,R16
	LDI				R16,32
	STS				$10A,R16			; BORRA LA O DE AUTO
LINEA1A:
	LDI				R16,80				; PONE UNA P
	STS				$10C,R16			; EN LA MEMORIA RAM DEL MICRO
	LDI				R16,104				; PONE UNA h
	STS				$10D,R16			; EN LA MEMORIA RAM DEL MICRO	
; NO ESCRIBE EL PH LOS PRIMEROS DOS MINUTOS
	LDS				R19,NCICLOS
	CPI				R19,00				; VERIFICA QUE A PASADO UN MINUTO PARA ENCENDER LA FUENTE
	BRBS			0,LINEA1_A			; SI ES MENOR DE DOS MINUTOS SALTA A VOLVER

	LDS				R19,MINU
	CPI				R19,02				; VERIFICA QUE A PASADO UN MINUTO PARA ENCENDER LA FUENTE
	BRBS			0,LINEA1_A			; SI ES MENOR DE DOS MINUTOS SALTA A VOLVER

	LDS				R24,RAM_PH			; LEE EL PH DE LA RAM
	RCALL			RADC				; RUTINA PARA CONVERTIR EN ANALOGICO
;	STS				$110,R1
	STS				$10F,R2				; RESULTADO DE DECENAS
	STS				$111,R3				; RESULTADO UNIDADES			
	LDS				R24,RAM_PH
	CPI				R24,100				; VALOR MAX DEL PH SOLO DOS CIFRAS
	BRBS			0, LINEA1_A			; SI ES MAYOR NO SALTA Y PONE E.E
	LDI 			R16,32
	STS				$10D,R16			; PONE UN ESPACIO 
	LDI				R16,69				; PONE E
	STS				$10F,R16
	LDI				R16,83				; PONE UNA S
	STS				$111,R16
	LDI				R16,46				; PONE .
	STS				$10F,R16

LINEA1_A:
	LDI				R16,192				; ESCRIBIR LINEA 2
	RCALL			ENVINT				; En subrrutina Env_doi Envia instrucion para escribir en linea 1
	LDI				YH, HIGH(LIN1)		; POSICION BIT ALTO DEL TEXTO A ENVIAR ram en 070
	LDI				YL, LOW(LIN1)		; POSICION BIT BAJO DEL TEXTO A ENVIAR
	LDI				R17,20				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			; RUTINA EN ESTE FICHERO PRECISA SUBRRUTINA ENV_DOI	
	RET	


.INCLUDE "NO_TECLA.ASM"

NIVEL_DEPOSITO:
	LDI				R16,192		; ESCRIBIR EN LINEA 2
	RCALL			ENVINT				; Y ENVIA EN MANSAJE A PANTALLA 1º INFORMACION DE LINEA Y....
	LDI				YH,HIGH(N_DEPOSITO) ;TEXTO A ENVIAR A PANTALLA "NIVEL DEPOSITO"
	LDI				YL,LOW(N_DEPOSITO) ;TEXTO A ENVIAR A PANTALLA
	LDI				R17,20				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			; 2º EL TEXTO 16 CARACTERES
	RET

LINEA2: ; RUTINA ESCRITURA LINEA2
	SBRS			VAL_LED,5			; VERIFICA EL LED 5 FALTA DE NIVEL EN EL DEPOSITO
	RJMP			LINEA10				; Y SALTA ESTA INSTRUCION SI ES UNO "HAY NIVEL"
	SBRS			LEC_REL,1
	RJMP			NIVEL_DEPOSITO		; VA CADA 3 SEGUNDOS AL MENSAJE DE "NIVEL DEPOSITO"

LINEA10:

	LDI				R16,83				; PONE UNA S
	STS				$115,R16
	LDI				R16,97				; PONE UNA a
	STS				$116,R16	
	LDI				R16,108				; PONE UNA l
	STS				$117,R16	
	LDI				R16,46				; PONE UN .
	STS				$11B,R16			; PUNTO DE LA SAL	
	STS				$124,R16			; PUNTO DEL PH
	LDI				R16,32				; CODIGO DEL ESPACIO			
	STS				$118,R16
	STS				$122,R16
	LDS				R24,RAM_SAL_C		; CARGA DE LA RAM EL VALOR DE LA MEDICION DE LA SAL
	CPI				R24,99
	BRBC			0,LINEA10_A

	CPI				R24,61
	BRLO			LINEA10_1
	LDI				R24,60				; SI ES MAYOR DE 60 PONE > Y DA VALOR DE 60 A SAL
	LDI				R16,62
	STS				$118,R16			; COLOCA EL SIMBOLO >			
LINEA10_1:
;	SUBI			R24,0				; RESTA UNA CANTIDAD COMO CONTENIDO DE CAL EN EL AGUA
	NOP
	RCALL			RADC
;	STS				$118,R1
	STS				$11A,R2				; VALOR DE LAS DECENAS
	STS				$11C,R3				; VALOR DE LAS UNIDADES
	RJMP			LINEA10_B
LINEA10_A:
	LDI				R16,45				; PONE UN -
	STS				$11A,R16
	STS				$11C,R16
LINEA10_B:
	LDI				R16,80				; PONE UNA P 
	STS				$11F,R16
	LDI				R16,104				; PONE UNA H
	STS				$120,R16
	LDI				R16,80 				; PONE UNA P
	STS				$121, R16	
	SBRS			CONTROL, 7 			; COMPRUEBA SI TIENE SONDA DE CLORO LIBRE
	RJMP			LINEA2A				; SI NO TIENE SALTA A LINEA2A
	LDS				R24, RAM_CL
	RCALL			RADC
	LDI				R16,32				; PONE UN ESPACIO PARA ELIMINAR LA P
	STS				$121,R16
	LDI				R16,67				; ESCRIBE UN C
	STS				$11F,R16
	LDI				R16,108 			; PONE UNA l
	STS				$120,R16	
	STS				$123,R2
	STS				$125,R3			
	RJMP			LINEA2B
LINEA2A: 		; CON SONDA DE REDOX
	SBRS			CONTROL,6			; COMPRUEBA SI TIENE SONDA DE REDOX
	RJMP			LINEA2C				; SI NO TIENE SALTA A LINEA 3A
	LDS				R24,RAM_RD
	RCALL			RADC5I				; RUTINA ESPECIAL PARA CONVERTIR EL REDOX EN BCD
	LDI				R16,32				; PONE UN ESPACIO PARA ELIMINAR LA P
	STS				$121,R16
	LDI				R16,82				; PONE UNA R
	STS				$11F,R16
	LDI				R16,100				; PONE UNA d
	STS				$120,R16
	STS				$123,R1
	STS				$124,R2	
	STS				$125,R3		
	RJMP			LINEA2B
LINEA2C:	
	LDS				R24,RAMP_PH
	RCALL			RADC	
;	STS				$120,R1
	STS				$123,R2
	STS				$125,R3			
;	RJMP			LINEA2B
;	LDI				R16,45				; PONE UNA -
;	MOV				R3,R16
;	MOV				R2,R16				; PONE UNA -
;	STS				$09D,R2	
;	STS				$09F,R3		

LINEA2B:
	LDI				R16,32
	STS				$126,R16			; LIMPIA LA PANTALLA
	STS				$127,R16
	STS				$128,R16
	LDI				R16,148				; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT
	LDI				YH,HIGH(LIN2)		; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL,LOW (LIN2)		; direccion BAJA DEL TEXTO EN RAM      	
  	LDI				R17,20 				; bytes a enviar 
	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO A PANTALLA
	RET
;       20x4        16x4   tipo de display
; linea 1-128 		128 
; linea 2-192		192
; linea 3-148		144
; linea 4-212		208

LINEA3:      
	LDI				R16,128				; ESCRIBIR LINEA 1 MODELO DEL EQUIPO
	RCALL			ENVINT				; En subrrutina Env_doi Envia instrucion para escribir en linea 1
	LDI				YH,HIGH(LIN1P)		; POSICION BIT ALTO DEL TEXTO A ENVIAR ram en 070
	LDI				YL,LOW (LIN1P)-2	; POSICION BIT BAJO DEL TEXTO A ENVIAR
	LDI				R17,20				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			; RUTINA EN ESTE FICHERO PRECISA SUBRRUTINA ENV_DOI
;	RET

;LINEA4: PONE EN PANTALLA 20X4 SEGUNDOS Y MINUTOS

	MOV				R24,LEC_REL
	RCALL			RADC

	STS				$569,R2
	STS				$56A,R3
	LDS				R24,MINU
	RCALL			RADC

	STS				$56E,R2
	STS				$56F,R3	
	LDS				R24,NCICLOS
	RCALL			RADC
;	STS				$24E,R2
	STS				$573,R3
;	LDI				R16,212			; 11000000 escribir en linea 4 linea (192)( linea 4 seria 212)
;	RCALL			ENVINT
;	LDI				YH,HIGH(PRO_CLORO)	; POSICION ALTA DEL TAXTO EN RAM 080
;	LDI				YL,LOW (PRO_CLORO)	; direccion BAJA DEL TEXTO EN RAM      	
 ; 	LDI				R17,20   			; bytes a enviar 
;	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO E PANRALLA

	RET




LIN_PGRAFICA:		;	************* PRESENTA EN NEXTION TODA LA INFORMACION


;CALL ENCENDER_GRA	; ENCIENDE LA PANTALLA GRAFICA

LDI R19,116				; LETRA t
LDI	R27,48				; LINEA 0
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (LIN1P)
LDI	YL, LOW (LIN1P)
;CALL P_NEXTION_TEXTO		;PRO_GRA_1		



LDI R19,116				; LETRA t
LDI	R27,49				; LINEA 1
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (LIN1P)
LDI	YL, LOW (LIN1P)
CALL P_NEXTION_TEXTO		;PRO_GRA_1		

LDI R19,116				; LETRA t
LDI	R27,50				; LINEA 2
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (LIN1)
LDI	YL, LOW (LIN1)
;CALL P_NEXTION_TEXTO		;PRO_GRA_1		

LDI R19,116				; LETRA t
LDI	R27,51				; LINEA 3
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (LIN2)
LDI	YL, LOW (LIN2)
;CALL P_NEXTION_TEXTO		;PRO_GRA_1		


LDI R19,116				; LETRA t
LDI	R27,52				; LINEA 4
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (PHP)
LDI	YL, LOW (PHP)
CALL P_NEXTION_TEXTO		;PRO_GRA_1		

LDI R19,116				; LETRA t
LDI	R27,53				; LINEA 5
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (PRUEBA_1)
LDI	YL, LOW (PRUEBA_1)
CALL P_NEXTION_TEXTO		;PRO_GRA_1		

LDI R19,116				; LETRA t
LDI	R27,54				; LINEA 6
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (L_BLANCA)
LDI	YL, LOW (L_BLANCA)
CALL P_NEXTION_TEXTO		;PRO_GRA_1		

LDI R19,116				; LETRA t
LDI	R27,55				; LINEA 7
LDI	R16,20				; 20 CARACTERES A ENVIAR
LDI	YH, HIGH (L_VOLTIOS)
LDI	YL, LOW (L_VOLTIOS)
CALL P_NEXTION_TEXTO		;PRO_GRA_1		

RET

ENVIARTEXTO_2: 
	LD				r16, Y+      		; carga byte en r0 e incrementa Y
	RCALL			ENVIARBYTE_2  		; lo enviamos 
	DEC				r17 				; descuenta uno
	BRNE			ENVIARTEXTO_2  		; si quedan mas seguimos enviando 
	RET


;.INCLUDE "SAA1064.ASM"
.INCLUDE "COMPARA2.ASM"
.INCLUDE "PRO_RD.ASM"
.INCLUDE "PRO_CL.ASM"	
.INCLUDE "PRO_PRO.ASM"
.INCLUDE "MED_PH+.ASM"
.INCLUDE "MED_SAL.ASM"
.INCLUDE "MED_CL.ASM"
.INCLUDE "MED_RD.ASM"
;.INCLUDE "AJUSTE_CL.ASM"
.INCLUDE "I2C_ATMEGA16.ASM"
;.INCLUDE "I2C_ATMEGA16_B.ASM"
;.INCLUDE "I2C_ATMEGA16_C.ASM"
.INCLUDE "DATOS.ASM"
.INCLUDE "PRO_CICLOS.ASM"
;.INCLUDE "RADIO.ASM"
.INCLUDE "PANEL_A.ASM"
.INCLUDE "TEXTO_LCD2.ASM"
;.CSEG 
;.ORG 0x0E90; 
;.INCLUDE "FRECUENCIMETRO.ASM"
;.INCLUDE "PI2C.ASM"				; esta opcion es con i2c del propio micro atmega16
;.CSEG 
;.ORG 0x0F20;    
.INCLUDE "AJUSTE_PRODUCION.ASM"
.INCLUDE "MULTIPLICAR.ASM"
;.INCLUDE "UART.ASM"
;.INCLUDE "RRADIO.ASM"
.INCLUDE "INI_ATMEGA64.ASM"						; PARAMETROS DE INICIALIZACION DEL MICRO
.INCLUDE "HORAS.ASM"
.INCLUDE "AYUDA_RD_CL.ASM"
.INCLUDE "VIDA_REJILLA.ASM"
.INCLUDE "CONTROL_CAUDAL.ASM"
;.INCLUDE "REMOTO_CONTROL.ASM"
.INCLUDE "VOLTIOS.ASM"
.INCLUDE "RETARDO240.ASM"
.INCLUDE "CALIBRAR_RD.ASM"
.INCLUDE "CALIBRAR_CL.ASM"

;*************TEXTO*************** 

.CSEG 
.ORG 0x1300;       
                        
TEXTO:		.DB "Rd000 S00 M00 C0"
			.DB "     -.- PHR 7.4"
TEXTO1:		.DB "PRODUCION %     " 
			.DB "EQUIPO DETENIDO "
			.DB "  -.-  Kgr/M3   "
;			           A  Ñ  A  D  I  R        S  A  L
			.DB "  A",00,"ADIR  SAL   "
			.DB "   A J U S T E  "
			.DB "  SIN  CAUDAL   "
			.DB " EQUIPO  REMOTO "
			.DB "   EN  MARCHA   "
			.DB " SIN PRODUCCION "
			.DB " NIVEL DEPOSITO "
			.DB "TEMPERATURA   . "
TEXTO2:		; se graba en ram en la rutina control de caudal
			.DB "   EN ESPERA    "
			.DB "      SEGUNDOS  "
			.DB "CONSULTAR MANUAL"
			.DB "  A V E R I A   "
			.DB "FALLO PRUDUCCION"
			.DB " Sust. Sonda Ph "
			.DB " ERROR CONEXION "
			.DB "VFu Vs P cl Temp"
			.DB "0.0 NO 00.0 --.-"
			.DB "Prod. Cl -- Gr/H" 

.CSEG 
.ORG 0x1400

TEXTO3: ; MODELO

			.DB "  50  80 120 180"		; VALORES DE POTENCIA DEL EQUIPO			
			.DB " 220  40  70 100"
TEXTO3A:
			.DB "  L  LS  LMG  Q "
			.DB " QS  QMG 123 456"
			.DB "                "
			.DB "                "
			.DB "                "
			.DB "                "
			.DB "                "
			.DB "                "
			.DB "                "
			.DB "                "
			.DB "                "
TEXTO4A:
			.DB "MT SALT         "			
			.DB "MASTERSALT      "					
			.DB "                "

;.CSEG 
;.ORG 0x0F80 
TEXTO4:
			.DB "MASTER  SALT    "
			.DB "MASTER  SALT    "
			.DB "MASTER  SALT    " 
			.DB "                "
			.DB "NUEVO CLIENTE 1 "
			.DB "NUEVO CLIENTE 2 "
			.DB "NUEVO CLIENTE 3 "
			.DB "NUEVO CLIENTE 4 "
			.DB "NUEVO CLIENTE 5 "
			.DB "NUEVO CLIENTE 6 "
			.DB "NUEVO CLIENTE 7 "
			.DB "NUEVO CLIENTE 8 "
			.DB "                "
TEXTO5:
			.DB "    EN ESPERA   "
			.DB "      SEGUNDOS  "

.CSEG 
.ORG 0x1504 ; COLOCACION EN FLASH 2A08
TEXTO6:		; PARA PANTALLA 20X4
			.DB "                    "
			.DB "                    "
			.DB "                    "
			.DB "pHp -.- pH agua  -.-"
			.DB " EFICACIA ELEC. ---%"
			.DB "TEMPERATURA --.- ",223,"C " ; LA Ñ ES 238
			.DB "PRO.TOTAL ---Gr/Cl/H"
			.DB "VALORES PROGRAMADOS "
			.DB "Ph -.- Rd --- Cl -.-"
TEXTO7:  ; SE PRESENTA AL PULSAR SALIR

			.DB "  Prod. por celda   "
			.DB "1-20 2-21 3-21 4-19 "
			.DB " Tension por celda  "
			.DB " 5.1  5.3  5.2  5.3 "


			.DB "Rd 000 S 00 M 00 C 0"
			.DB "pHp  -.- PHR 7.4    "
			.DB "PRODUCCION    %     " 
			.DB "   EQUIPO DETENIDO  "
			.DB "A",04,"ADIR SAL -.-Kgr/M3"
;			           A  Ñ  A  D  I  R        S  A  L
			.DB "  A",04,"ADIR  SAL       "
			.DB "    A J U S T E     "
			.DB "  SIN  CAUDAL       "
TEXTO8:		.DB "   EQUIPO  REMOTO   "
			.DB "     EN  MARCHA     "
			.DB "   SIN PRODUCCION   "
			.DB "   NIVEL DEPOSITO   "
			.DB "Temperatura    .  ",223,"C" ; PRESENTAR º O CREARLO
			.DB "                    "
			.DB "  SENSOR DE FLUJO   "
			.DB "    EN  ESPERA      "
			.DB "       SEGUNDOS     "
			.DB "  CONSULTAR  MANUAL "
			.DB "    A V E R I A     "
			.DB "  FALLO PRUDUCCION  "
TEXTO9:		.DB "   Sust. Sonda Ph   "
			.DB "   ERROR CONEXION   "
			.DB "VFu Vs Amp  Temp    "
			.DB "0.0 NO 00.0 --.-    "
			.DB " Pro.cloro -- Gr/H  " 
			.DB " En espera   ---Seg "
			.DB " Comprobar conexion "
			.DB "   Cable electrodo  "
			.DB "Vida electrodo  ---%"
			.DB "                    "
			.DB "SAL EN AGUA  -.- g/l"
			.DB " A",04,"ADIR -,- g/l     "
TEXTO10:
			.DB "CALIBRAR SAL -.- g/l"
			.DB "CALIBRAR pH  N/D    "
			.DB "CALIBRAR Rdx N/D mV "
			.DB "CALIBRAR Cl  N/D ppm"
			.DB "Nivel de prod ---%Cl"
			.DB "pH max en agua N/D  "
			.DB "Nivel Rdx agua N/DMv"
			.DB "Nivel Cl agua N/Dppm"
			.DB "Invertir Pol cada -h"
			.DB "Prod. Auto Rdx ---mV"	
			.DB "Prod. Auto Cl -.-ppm"
			.DB "Uso del equipo ----H"
TEXTO11:		; INSTRUCCIONES NEXTION TEXTO
			.DB "page 0  pic  t0.txt="
			.DB "j0.val= 1    N0 SI  "
			.DB "t5.bco=50712        "				; 12 gris claro
		    .DB "t5.bco=2016         "				; 11 verde
			.DB "Redox mmV           "
			.DB "Cloro ppm     q00 	 "				; q00 PARA QUE EL MICRO VALLA A PAGINA CERO PRINCIPAL
			.DB "pic 441,25,36       "				; ENVIA POLARIDAD 1 o 2	 1 ES 36 2 ES 35		
			.DB "  Exceso de Sal     "
			.DB "SHUNT      MOS      "
			.DB "                    "
.equ	VERDE=0xA38
.equ	ROJO=0xA24
.CSEG 
.ORG 0x1800 ; COLOCACION EN FLASH 2E90


.INCLUDE "PRO_RD_CL.ASM"
.INCLUDE "RETARDO.ASM"
.INCLUDE "VER_ERROR.ASM"
.INCLUDE "MED_INI_SAL.ASM"
.INCLUDE "PANTALLA2.ASM"
;.INCLUDE "P_GRAFICO.ASM"
;.INCLUDE "TEXTO_LCD.ASM"
.INCLUDE "DESGASTE_ELECTRODO.ASM"
.INCLUDE "SCR.ASM"
.INCLUDE "BORRAR_EEPROM.ASM" ; RUTINA A ELIMINAR BORRA LA EPROM INTERNA DEL MICRO
;       20x4        16x4   tipo de display
; linea 1-128 		128 
; linea 2-192		192
; linea 3-148		144
; linea 4-212		208
BORRAR_PANTALLA:
	LDI				R16,128			; BORRAR LINEA 1
	CALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION
	LDI				YH,HIGH(BORRAR_LINEA)	; POSICION ALTA DEL TAXTO EN RAM 7A4
	LDI				YL,LOW (BORRAR_LINEA)	; direccion BAJA DEL TEXTO EN RAM
  	LDI				R17,20   			; bytes a enviar 
	CALL			ENVIARTEXTO	
	LDI				R16,192			; BORRAR LINEA 2
	CALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION
	LDI				YH,HIGH(BORRAR_LINEA)	; POSICION ALTA DEL TAXTO EN RAM 7A4
	LDI				YL,LOW (BORRAR_LINEA)	; direccion BAJA DEL TEXTO EN RAM
  	LDI				R17,20   			; bytes a enviar 
	CALL			ENVIARTEXTO	
	LDI				R16,148			; BORRAR LINEA 3
	CALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION
	LDI				YH,HIGH(BORRAR_LINEA)	; POSICION ALTA DEL TAXTO EN RAM 7A4
	LDI				YL,LOW (BORRAR_LINEA)	; direccion BAJA DEL TEXTO EN RAM 	
  	LDI				R17,20   			; bytes a enviar 
	CALL			ENVIARTEXTO	
borra_linea_4:
	LDI				R16,212			; BORRAR LINEA 4
	CALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION
	LDI				YH,HIGH(BORRAR_LINEA)	; POSICION ALTA DEL TAXTO EN RAM 7A4
	LDI				YL,LOW (BORRAR_LINEA)	; direccion BAJA DEL TEXTO EN RAM
  	LDI				R17,20   			; bytes a enviar 
	CALL			ENVIARTEXTO	
	RET
.INCLUDE "UART0.ASM"
.INCLUDE "UART1.ASM"
.INCLUDE "PRO_PAR.ASM"
.INCLUDE "P_NEXTION_RS0.ASM"
.INCLUDE "PWM_ATMEGA.ASM"
.INCLUDE "SERVO.ASM"
.INCLUDE "MOTOR_PAP.ASM"

.INCLUDE "CONTROL_ELECTRODO.ASM"

;.org SMALLBOOTSTART ;	= 0x7e00 que es fc00
;.INCLUDE "FLASH_SPM.ASM"
;.INCLUDE "CONTROL_REMOTO.ASM"
;****HASTA AQUÍ EL PROGRAMA******* 


