

;     PROGRAMA PRINCIPAL
; CONTROL LINEA 0 SE UTILIZA EN RUTINA COMPARA
; CONTROL LINEA 1 SE UTILIZA EN LA TRANSMISION POR RADIO, INTERRUPCION TIMER2_OVF
; CONTROL LINEA 2 VERANO Ó INVIERNO A 1 INVIERNO
; CONTROL LINEA 3 MAXIMA PRODUCION SE ACTIVA EN RUTINA TECLADO ACTUA EN RUTINA RELOJ
; CONTROL LINEA 4 SONDA DE Ph PRESENTE
; CONTROL LINEA 5 CICLO PARA VERIFICAR UNA VEZ POR SEGUNDO
; CONTROL LINEA 6 SONDA DE REDOX PRESENTE
; CONTROL LINEA 7 SONDA CLORO LIBRE PRESENTE

; CONTROL_1 LINEA 0 SE ACTIBA UNA VEZ POR SEGUNDO
; CONTROL_1 LINEA 1 OPCION UTILIZAR ACIDO Ó SOSA
; CONTROL_1 LINEA 2 PARA ANULAR LA MEDICION DE CLORO Y REDOX LA ANULA ESTANDO A UNO
; CONTROL_1 LINEA 3 PARA ACTIVAR LA OPCION DE CALCULAR EL PORCENTAJE DE PRODUCION
; CONTROL_1 LINEA 4 FUENTE
; CONTROL_1 LINEA 5 RETARDO 240 SEGUNDOS EN INICIO 

;   CONTROL DE LOS LED
;	0	FUNCIONAMIENTO DE LA FUENTE
;	1	VERANO INVIERNO
;	2	INTERMITENTE
;	3
;	4	LED DE PH
;	5	NIVEL DE ACIDO BAJO NO ESTA PRESENTE EN LA PANTALLA
;	6	LUZ PANTALLA
;	7	POLARIDAD


; SITUACION DE LOS MENSAJES EN RAM
	.equ		PILA		=0x45F				; PARA EL REGISTRO DE INTERRUPCIONES EN RAM
	.equ		LIN1		=0x070				; LINEA 1 DE LA PANTALLA EN RAM
	.equ		LIN2		=0x090				; LINEA 2 DE LA PANTALLA EN RAM
	.equ		LIN3		=0x0A0				; LINEA PARA TRANSMITIR EN LA UART
	.equ		L_HORAS 	=0x0B0				; LINEA 1 DE LA PANTALLA EN RAM PRESENTACION DE LAS HORAS
	.equ		LIN_2P		=0x1E0				; LINEA 2 DE PROGRAMACION DE MOMENTO "SIMULACION"
	.equ		PRUEBA_2	=0x220				; TEXTO
	.equ		PRUEBA_3	=0x230				; TEXTO
	.equ		PRUEBA_1	=0x240				; ES LA LINEA 4 EN RAM
	.equ		PRUEBA		=0x250				; ES LA LINEA 3 EN RAM
	.equ		POR_PRO		=0x260				; PRODUCION % 
	.equ		LIN_2S		=0x270				; TEXTO " EQUIPO DETENIDO "
	.equ		A_SAL		=0x280				; TEXTO "  -.- gr/litro "
	.equ		LIN_REJILLA =0x290				; TEXTO "  AÑADIR SAL   "
	.equ		LIN_1P		=0x2A0				; LINEA 1 DE PROGRAMACION " AJUSTE"
	.equ		LIN_CA		=0X2B0				; TEXTO  "SIN CAUDAL "
	.equ		E_REMOTO	=0x2C0				; TEXTO " EQUIPO REMOTO "
	.equ		E_MARCHA	=0x2D0				; TEXTO " EN MARCHA "
	.equ		E_PROD		=0x2E0				; TEXTO " SIN PRODUCCION "
	.equ		N_DEPOSITO	=0x2F0				; TEXTO " NIVEL DEPOSITO "
	.equ		LIN4		=0x300				; LINEA PRESENTACION DE LA TEMPERATURA
	.equ		LIN1P		=0x310				; LINEA PRIMERA PRESENTACION  "MODELO DE EQUIPO PRESELECIONADO"
	.equ		LIN2P		=0x320				; LINEA SEGUNDA PRESENTACION  " TEAP Ó DISTRIBUIDOR"
	.equ		EN_ESPERA	=0x330				; TEXTO EN ESPERA
	.equ		N_SEG		=0x340				; PRESENTA LOS SEGUNDOS QUE FALTAN EN ERROR
	.equ		C_MANUAL	=0x350				; TEXTO " CONSULTAR MANUAL"
	.equ		AVERIA		=0x360				; TEXTO "  A V E R I A   "
	.equ		F_PRO		=0x370				; TEXTO "PALLO PRODUCCION"
	.equ		F_CONEX		=0x390				; TEXTO "FALLO CONEXION"
	.equ		L_BLANCA	=0x3A0
.DSEG											; DIRECION INICIAL DE LA PILA EN MEMORIA RAMM
.ORG			PILA							; POSICION EN RAM 0x16F DEFINIDO EN LINEA 11 DE ESTE FICHERO 
.CSEG											; GRABAR EL PROGRAMA EN LA FLASH
.ORG			0x0000							; DIRECCION DE INICIO PROGRAMA POSICION DE MEMORIA 0X0000							; 




	 	RJMP		RESET							; 1 External Pin, Power-on Reset, Brown-out
NOP
	RJMP		INT_0							; 2 External Interrupt Request 0
NOP
	RJMP		INT_1							; 3 External Interrupt Request 1
NOP
	RJMP		TIMER2							; 4 COMP Timer/Counter2 Compare Match
NOP
	RJMP		TIMER2_OVF						; 5 Timer/Counter2 Overflow
NOP
	RJMP		TIMER1_CAPT						; 6 Timer/Counter1 Capture Event
NOP	
	RJMP		TIMER1_COMPA					; 7 Timer/Counter1 Compare Match A
NOP
	RJMP		TIMER1_COMPB					; 8 Timer/Counter1 Compare Match B
NOP	
	RJMP		TIMER1_OVF						; 9 Timer/Counter1 Overflow
NOP
	RJMP		TIMER0_OVF						; 10Timer/Counter0 Overflow
NOP
	RJMP		SPI_STC							; 11Serial Transfer Complete
NOP
	RJMP		USART_RXC_USART					; 12Rx Complete
NOP
	RJMP		USART_UDRE_USART				; 13Data Register Empty
NOP
	RJMP		USART_TXC_USART					; 14Tx Complete
NOP
	RJMP		ADC_ADC							; 15Conversion Complete
NOP
	RJMP		EE_RDY_EEPROM					; 16Ready
NOP
	RJMP		ANA_COMP						; 17Analog Comparator
NOP
	RJMP		TWI								; 19Two-wire Serial Interface
NOP
	RJMP		INT_2							; 19External Interrupt Request 2
NOP
	RJMP		TIMER0_COMP						; 20Timer/Counter0 Compare Match
NOP
	RJMP		SPM_RDY							; 21Store Program Memory Ready
;.INCLUDE "Uart.asm"


.INCLUDE "AJUSTE_PRESENTACION.ASM"
.INCLUDE "PARAMETROS_I2C.ASM"
.INCLUDE "M16DEF.INC"			; DEFINICION DE REGISTROS
.INCLUDE "PARAMETROS.ASM"		; VALORES ESPECIFICOS

.INCLUDE "I2CP.ASM"    			; esta opcion es con i2c programado
.INCLUDE "ADC.ASM"
.INCLUDE "ini_pan.asm"
.INCLUDE "INI_PANTALLA_2.ASM"
.INCLUDE "RELOJ.ASM"
.INCLUDE "LINEA_PH.ASM"
.INCLUDE "LEC_TEC.ASM"
.INCLUDE "ENV_DOI.ASM"			; ENVIO A PANTALLA 1
.INCLUDE "ENV_DOI_2.ASM"		; ENVIO A PANTALLA 2
.INCLUDE "EEPROMRW.ASM"
.INCLUDE "CON_ADC.ASM"
.INCLUDE "COMPARA.ASM"
.INCLUDE "CALIBRARSAL.ASM"
.INCLUDE "CALIBRARCL.ASM"
.INCLUDE "PCF8591.ASM"

INT_0:									; RESET						 			0x002
	RETI
INT_1:									; INTERRUPCION EXTERNA 0 				0x004
	RETI
TIMER2:									; INTERRUPCION EXTERNA 1	 			0x006
	RETI
TIMER2_OVF:								; Pin Change Interrupt Request0			0x008
	SBR			CONTROL,0B00000010		; PONE A UNO EL BIT 1

	RETI
TIMER1_CAPT:							; Pin Change Interrupt Request1			0x00A
	RETI
TIMER1_COMPA:							; Timer/Counter3 Capture Event 7 		0x00C
in r10, sreg
push r10
	PUSH		R17
	LDI			R17, 00
	OUT			TCNT1L, R17		
	OUT			TCNT1H, R17
	INC			temp_tec
;	LDS			R17, CEN_SEG
;	INC			R17
;	CPI			R17,1
;	BRBS		0, TIMER1_COMPA_1		
;	LDI			R17, 0
	INC			LEC_REL					; INCREMENTA LOS SEGUNDOS DEL RELOJ
	SET									; PONE A 1 EL REGISTRO T DE SREG
	BLD			CONTROL_1, 0			; LINEA DE CONTROL 5 ACTIVADA UNA VEZ POR SEGUNDO
TIMER1_COMPA_1:
	STS			CEN_SEG, R17

POP R17
pop r10
out sreg, r10
	RETI
TIMER1_COMPB:							; Timer/Counter3 Compare Match A 		0x00E
	RETI
TIMER1_OVF	:							; Timer/Counter3 Compare Match B  		0x010
	RETI
TIMER0_OVF:								; Timer/Counter3 Overflow 				0x012
in r10, sreg
push r10
	INC			R22
pop r10
out sreg, r10
	RETI
SPI_STC:								; Timer/Counter2 Compare Match			0x014
	RETI
USART_RXC_USART:						; Timer/Counter2 Overflow				0x016
	RETI
USART_UDRE_USART:						; Timer/Counter1 Capture Event			0x018
	RETI
USART_TXC_USART:						; Timer/Counter1 Compare Match A		0x01A
	RETI
ADC_ADC:								; Timer/Counter1 Compare Match B		0x01C
	RETI
EE_RDY_EEPROM:							; Timer/Counter1 Overflow				0x01E
	RETI
ANA_COMP:								; Timer/Counter0 Compare Match			0x020
	RETI
TWI:									; Timer/Counter0 Overflow				0x022
	RETI
INT_2:									; Serial Transfer Complete				0x024
	RETI
TIMER0_COMP:							; TIMER 0 POR COMPARACION 				0x026

	RETI
SPM_RDY:								; USART1, Rx Complete					0x028
	RETI

RESET:

	LDI				R16,HIGH (PILA)		; Coloca en el start point de 16 bits la 
	OUT				SPH,r16 			; direcion de inicio para las interrupciones
	LDI				R17,LOW (PILA )		; y uso de las instruciones PUHS y POP      
	OUT				SPL,r17 


; *********INICIALIZAR PANTALLA //////////////


	CALL			INI_ATMEGA16 		; INICIALIZAR PARAMETROS
	CALL			INI_LCD_2			; CARGO EL TEXTO DE LA PANTALL 2

CALL PANTALLA
	SER				R16
	MOV				VAL_LED, R16
	RCALL			LEDPANT
	RCALL 			INI_PANTALLA		; LLAMA A LA RUTINA PARA INICIAR LA PANTALLA
RCALL INI_PANTALLA_2
	RCALL			INI_PANTALLA1		; RUTINA PRESENTACION DE DATOS
	LDI   			LEC_REL, 00			; PONE A CERO EL CONTADOR DEL RELOJ	
RET1:
	CPI	  			LEC_REL,2			; VALOR DEL TIEMPO DE RATARDO PRESENTACION
	BRLO  			RET1				; COMPRUEBA EL TIEMPO DE RETARDO SI ES MENOR DE 2 A RET1
	LDI   			YH,high(LIN_2S)		; direccion alta del TEXTO en Ram
	LDI   			YL,low (LIN_2S)		; direccion baja del TEXTO en Ram 
;	RCALL			UART_INI
	LDI				LEC_REL, 50			; VALOR INICIAL RETARDO DE ENCENDIDO
	LDI				R25,51				;Valor para configurar 9600BPS A 8MH de la UART 51para 11.059 71
	LDI				CONTROL, 0
; PARAMETROS INICIALES LECTURA DEL PORCENTAJE DE PRODUCION EN CASO DE CUBIERTA CERRADA
	LDI 			R17, RE_PRO
	CALL			EEPROM_RW
	STS				RAM_PRO_PRO, R18
; ACTIVACION DE LA BOMBA DE APOYO PARA CLORE Y SEDOX
	LDI				R17, apoyo_rd_cl	; POSICION EN EEPROM
	RCALL			EEPROM_RW			; RUTINA DE LECTURA DE EPROM
	CPI				R18, 7				; COMPARA CON 5
	BRLO			RD_CL1				; SI ES MENOR VA A RD_CL1
	LDI				R18, 6
	RCALL			EEPROM_ES			; ACTUALIZA LA EEPROM CON 4
RD_CL1:
	STS				ram_rd_cl, R18		; PASA A RAM EL VALOR

; PARAMETROS NUMERO DE CICLOS PARA LA INVERSION
 	LDI				R17, ciclos_minuto	; POSICION DEL PH PROGRAMADO EN EEPROM $000
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	CPI				R18, 5				; COMPARA CON 5 SI ES MAYOR RECTIFICA EL VALOR
	BRLO			SALTA_1
	LDI				R18, 4				; Y PONE 4
	MOV				R19, R18
SALTA_1:
	STS				RAM_CICLOS, R18
	LDI				R17, CICLOS_MINUTO
	RCALL			EEPROM_ES			; ACTUALIZA LA EEPROM CON EL VALOR INICIAL
	LDI				R17, EE_CICLOS
	ADD				R17, R18
	CALL			EEPROM_RW
	INC				R18
	CPI				R18, 200			; SI ES MAYOR DE 200 PONE EL REGISTRO A CERO
	BRBC			0, SALTA2			; Y SALTA A 2 PORA INCREMENTAR EL SEGUNDO REGISTRO
	CALL			EEPROM_ES
	RJMP			SALTA3
SALTA2:
	LDI				R18, 0				; GRABA CERO 
	CALL			EEPROM_ES
	LDI				R19, 16
	ADD				R17, R19
	CALL			EEPROM_RW			; LEE EL REGISTRO ALTO
	INC				R18					; Y LO INCREMENTA EN 1 UNIDAD
	CALL			EEPROM_ES			; Y LO GRABA


SALTA3:
; PARAMETROS INICIALES AJUSTADOS DEL PH
 	LDI				R17, PH_MEN			; POSICION DEL PH PROGRAMADO EN EEPROM $000
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, PH_MAX
	RCALL			COMP
	SBRC			CONTROL, 0
	LDI				R18, 74
	LDI				R25, PH_MIN
	RCALL			COMP
	SBRS			CONTROL, 0
	LDI				R18, 74				; SI SE MENOR PONE EL PH NORMAL
	LDI				R17, PH_MEN
	RCALL			EEPROM_ES			; ACTUALIZA LA EEPROM CON EL VALOR INICIAL
	STS				RAMP_PH, R18		; GRABAR EN LA MEMORIA RAM EL VALOR PROGRAMADO DEL PH $1D1

; CALIBRACION SONDA DE PH	 VALOR ENTRE 20 Y CERO INICIAL 10
	LDI				R17, PHC_MEN		; POSICION DE MEMORIA A LEER EN EEPROM $005
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, 20
	RCALL			COMP				; COMPARA R18 CON R25
	SBRC			CONTROL, 0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18, 10
	STS				RAMC_PH, R18		; VALO CALIBRACION PH $1D2
	LDI				R17, PHC_MEN
	RCALL			EEPROM_ES			; ACTUALIZA EL VALOR INICIAL DEL PH
	LDI				R24, 74				; VALOR INICIAL DE MEDICION DEL PH
	STS				RAM_PH, R24			; ALMACENA EN LA MEMORIA RAM EL PH $1D0

; PARAMETROS INICIALES AJUSTE DE LA SAL


; CALIBRACION MEDICION CONCENTRACION DE SAL	NUMERO DE MEDICIONES ENTRE 50 Y 180 EN CASO CONTRARIO PONE 100
	LDI				R17, SAC_MEN		; POSICION DE MEMORIA A LEER EN EEPROM $006
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, 181
	RCALL			COMP				; COMPARA R18 CON R25
	SBRC			CONTROL, 0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18, 120
	LDI				R25, 50
	RCALL			COMP
	SBRS			CONTROL, 0
	LDI				R18, 120			; SI SE MENOR PONE EL PH NORMAL
	LDI				R17, SAC_MEN
	RCALL			EEPROM_ES			; GUARDA EN EEPROM EL VALOR INICIAL DE 100
	STS				RAMC_SAL, R18		; VALOR CALIBRACION SAL $1DD
	LDI				R24, 120				; VALOR INICIAL DE MEDICION DE LA SAL
	STS				RAM_SAL, R24		; ALMACENA EN LA MEMORIA RAM
	STS				RAM_SAL_C, R24		; ALMACENA LA MEDICION EN LA MEMORIA RAM

; PARAMETROS INICIALES DE CLORO LIBRE
	LDI				R17, CL_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $002
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, CL_MAX + 1
	RCALL			COMP
	SBRC			CONTROL, 0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18, 10
	LDI				R25, CL_MIN
	RCALL			COMP
	SBRS			CONTROL, 0
	LDI				R18, 8				; SI SE MENOR PONE EL PH NORMAL
	STS				RAM_CL, R18			; GRABAR EN LA MEMORIA RAM $1D6
	STS				RAMP_CL, R18		; GRABAR EN LA MEMORIA RAM $1D7
	WDR

; PARAMETROS INICIALES AJUSTE DE LA SONDA DE CLORO LIBRE
	LDI				R17, CLC_MEN		; POSICION DE MEMORIA A LEER EN EEPROM $004
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, 250			; VALOR MAXIMO
	RCALL			COMP
	SBRC			CONTROL, 0			; VERIFICA SI ES CERO EL BIT 7 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18, 200			; VALOR ESTANDAR
	LDI				R25, 150			; VALOR MINIMO
	RCALL			COMP				; RUTINA COMPARACION
	SBRS			CONTROL, 0
	LDI				R18, 200			; SI ES MENOR PONE EL NORMAL
	STS				RAMC_CL, R18		; GRABA EL VCALOR DE CALIBRACION DEL CLORO $1D8
	WDR

; PARAMETROS INICIALES DEL REDOX programados
	LDI				R17, RD_MEN			; POSICION DE MEMORIA A LEER EN EEPROM $003
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, RD_MAX	+ 1		; REDOX MAXIMO 170X5=850
	RCALL			COMP
	SBRC			CONTROL, 0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18, 148			; REDOX PREFIJADO
	LDI				R25, RD_MIN			; REDOX MINIMO
	RCALL			COMP
	SBRS			CONTROL, 0
	LDI				R18, 148			; REDOX PREFIJADO
	STS				RAM_RD, R18			; GRABAR EN LA MEMORIA RAM $1D9
	STS				RAMP_RD, R18		; GRABAR EN LA MEMORIA RAM $1DA
	WDR
; VALORES DE CALIBRACION DEL REDOX, 230 MEDICIONES
	LDI				R17, RDC_MEN		; POSICION DE MEMORIA A LEER EN EEPROM $007
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, 254			; VALOR MAXIMO
	RCALL			COMP
	SBRC			CONTROL, 0			; VERIFICA SI ES CERO EL BIT 7 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18, 237			; VALOR ESTANDAR
	LDI				R25, 200			; VALOR MINIMO
	RCALL			COMP				; RUTINA COMPARACION
	SBRS			CONTROL, 0
	LDI				R18, 237			; SI SE MENOR PONE EL NORMAL
	STS				RAMC_RD, R18		; GRABA EL VCALOR DE CALIBRACION DEL CLORO $1DB


; parametros iniciales de la producion
	LDI				R17, PRO_MEN		; POSICION DE MEMORIA A LEER EN EEPROM $001
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	LDI				R25, PRO_MAX + 1
	RCALL			COMP
	SBRC			CONTROL, 0			; VERIFICA SI ES CERO EL BIT 0 SI ES CIERTO SALTA LA SIG. INSTRUCION
	LDI				R18, 90
	LDI				R25, PRO_MIN
	RCALL			COMP
	SBRS			CONTROL, 0
	LDI				R18, 90				; SI SE MENOR PONE EL PH NORMAL
	STS				RAM_PRO, R18		; GRABAR EN LA MEMORIA RAM $1D4
	STS				RAMP_PRO, R18		; GRABAR EN LA MEMORIA RAM $1D5
	WDR

	LDI				R24, 00				; VALOR INICIAL PARA ACTIVAR EL PERRO GUARDIAN
	OUT				WDTCR, R24			; ACTIVA EL PERRO GUARDIAN
	CLR				CONTROL
	CBI				PORTD, 4			; APAGA VENTILADOR Y CONTROL REMOTO
	CLR   			R16
	STS  			seg,  R16			; PONE A CERO LOS SEGUNDOS
	STS   			minu, R16			; PONE A CERO LOS MINUTOS
	STS   			hora, R16			; PONE A CERO LAS HORAS
	MOV				VAL_LED, R16
	RCALL			LEDPANT
	CBI				PORTD,B_ACIDO		; APAGA BOMBA DE ACIDO
; OPCION VERANO INVIERNO
	LDI				R17, VER_INV		; POSICION DE MEMORIA A LEER EN EEPROM $1DE
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	BST				R18, 0				; ALMACENA EL BIT CERO EN EL REGISTRO T DE SREG
	BRTC			INVIERNO_A			; SALTA A INVIERNO SI ES CERO
	RJMP			VERANO_A
INVIERNO_A:
	LDI				R17, EE_CICLOS
	CALL			EEPROM_RW
	INC				R18
	CPI				R18, 200			; SI ES MAYOR DE 200 PONE EL REGISTRO A CERO
	BRBC			0, SALTA2A			; Y SALTA A 2 PORA INCREMENTAR EL SEGUNDO REGISTRO
	CALL			EEPROM_ES
	RJMP			SALTA3A
SALTA2A:
	LDI				R18, 0				; GRABA CERO 
	CALL			EEPROM_ES
	LDI				R19, 16
	ADD				R17, R19
	CALL			EEPROM_RW			; LEE EL REGISTRO ALTO
	INC				R18					; Y LO INCREMENTA EN 1 UNIDAD
	CALL			EEPROM_ES			; Y LO GRABA
SALTA3A:
	MOV				R16, VAL_LED
	ORI				R16, 0B00000010		; ENCIENDE LED VERANO INVIERNO
	MOV				VAL_LED, R16
	SBR				CONTROL, 0B00000100	; ACTIVA LA SEÑAL DE INVIERNO EN CONTROL
VERANO_A:


; OPCION PRODUCION AUTOMATICA O ANULACION DE LA MEDICION DE CLORO Y REDOX
	LDI				R17, PA_PM
	CALL			EEPROM_RW
	BST				R18, 0				; PASA EL REGISTRO 0 DE R18 A T		
	BLD				CONTROL_1,2			; PASA EL REGISTRO T DE SREG A CONTROL1_2
; POR ERROR EN EL SIMULADOR DESACTIVA LA PRESENTACION DE AÑADIR SAL
	SET									; PONE ES REGISTRO T A 0 SET LO PONE A 1
	BLD				CONTROL_1, 5		; PASA EL REGISTRO T A CONTROL_1
; OPCION INICIO DE POLARIDAD
	LDI				R17, POL_MEN		; POSICION DE MEMORIA A LEER EN EEPROM $1DE
;	RCALL			I2CL_2404			; A LA RUTINA DE LECTURA DE LA EEPROM
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	STS				RAM_POL, R18
	LDI				R17, POL_MEN		; POSICION EN EEPROM DE LA POLARIDAD
	LDS				R18, RAM_POL		; VALOR POLARIDAD CICLO ANTEIOR
	INC				R18					; INCREMENTAMOS UNO			
;	RCALL			I2CE_2404			; ESCRIBE EL NUEVO VALOR EN LA EEPRON EXTERNA
	RCALL			EEPROM_ES
	BST				R18, 0				; ALMACENA EL BIT MENOS IMPORTANTE DE LA MEDICION DEL PH EN EL REGISTRO T DE SREG
	BRTC			RELE_POLARIDAD		; SI ESE BIT ES CERO 
;	BLD				VAL_LED, 3			; Y LA PASA AL CONTROL DE POLARIDAD	PARA NO APAGAR EL RELE Y ACTIBAR LED
	BLD				VAL_LED, 7			; ESTE ES EL LED DE SAL QUE NO VALE PA NA
	SBI				PORTD, 6			; APAGA RELE POLARIDAD 1
	RJMP			REMOTO
RELE_POLARIDAD:
	SBI				PORTD, 7			; APAGA RELE POLARIDAD 2

; TERMINA INICIALIZACION DEL PROCESO ********************************************************/////

; ********* PROGRAMA PRINCIPAL //////////////// AQUI PROGRAMA PRINCIPAL *************************

REMOTO:
; RETARDO PARA VALENCIA 240 SEGUNDOS
	LDI				R17, retardo_inicio
	RCALL			EEPROM_RW			; RUTINA LECTURA EEPROM DEVUELVE EL VALOR EN R18
	CPI				R18, 1				; SI ES UNO VA A RUTINA DE RETARDO
	BRNE			REMOTO23			; COMO ES DISTINTO VA A REMOTO23
	RCALL			RETARDO240			; RUTINA DE RETARDO240
REMOTO23:
	SET
	BLD				CONTROL_1, 4
	CALL			COMPARA2
	LDI				R19, 00
	STS				NCICLOS, R19		; LIMPIA LA POSICION NCICLOS en ram
	STS				MINU, R19
	LDI				R19, 20
	MOV				LEC_REL, R19
	SBIS			PINB, 3				; VERIFICA QUE FUENTE TIENE LA 150 CON PUENTE
	SBR				CONTROL,0B00000010	; PONE A UNO EL BIT 1 SI HAY PUENTE
	CALL			MED_INI_SAL			; LEE EL VALOR INICIAL DE LA SAL PARA ELIMINAR EL ERROR
	SBIS			PINB, 4				; PRINCIPAL O REMOTO salta la siguiente instrucion si es uno
	RJMP			REMOTO1				; SI HAY PUENTE REMOTO
	LDI				R18, 10				; PONE EL CONTADOR DE SEGUNDOS A 10
	STS				RAM_CAUDAL, R18		; LIMPIA DE SEGUNDOS EL CONTROL DE CAUDAL ENPIEZA EN 10 SEGUNGOS
; LINEA 5 6 Y 7 DEL PUERTO B COMO SALIDA
LDI				R16,0B11100111	;PUERTO 4 REMOTO Y 3 TIPO DE FUENTE COMO ENTRADA SEÑAL
OUT   			DDRB, R16		; PUERTO 5 6 Y 7 ENTRADA DEL MESTRO
	RJMP			PRO					; NO HAY PUENTE PROGRAMA MAESTRO

										; PROGRAMA DEL EQUIPO REMOTO
REMOTO1: ;CAMBIAMOS EL TEXTO EN LA MEMORIA RAM
;   LDI   			YH,0x01        		; direcion alta donde se pone el texto en RAM
;   LDI   			YL,0xE0      		; direccion baja donde se pone el texto en RAM 
;   LDI   			ZH,high(TEXTO2*2)	; direccion alta del TEXTO en Flash
;   LDI   			ZL,low(TEXTO2*2) 	; direccion baja del TEXTO en Flash 
;   LDI   			R16,48      		; longitud de texto a copiar en RAM
;*** RURINA CARGAR TEXTO DE FLASH A RAM  
;EN Y (YH,YL) POSICION EN RAM
;EN Z (ZH,ZL) POSICION EN FLASH
;EN R16 NUMERO DE LETRAS (BYTS)
CARGATEXTO1:
;	LPM      							; leemos TEXTO de FLASH y lo almacena en R0
;	ADIW  			ZL,1   				; apuntamos al siguiente elemento 
;	ST    			Y, R0				; guardamos en RAM POSICION Y EL CONTENIDO DE R0
;	ADIW  			YL,1      			
;	DEC   			R16      			; Hemos terminado..?? 
;	BRNE  			CARGATEXTO1   		; NO...seguimos cargando 
; ELIMINADO PARA NO UTILIZAR LA PANTALLA
	LDI				R16, 192			; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2";	LDI				YH, HIGH (E_PROD)	; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YH, HIGH (AVERIA)
	LDI				YL, LOW  (AVERIA)	; direccion BAJA DEL TEXTO EN RAM  " SIN PRODUCCION 
	LDI				R17,16   			; bytes a enviar 
	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO E PANTALLA
	CBI				PORTD,B_ACIDO		; APAGA BOMBA DE ACIDO
LDI				R16,0B00000111	;PUERTO 4 REMOTO Y 3 TIPO DE FUENTE COMO ENTRADA SEÑAL
OUT   			DDRB, R16		; PUERTO 5 6 Y 7 ENTRADA DEL MESTRO
LDI				R16,0B11111110	;PUERTO 4 Y 3 COMO ENTRADA SEÑAL PARA EL CONTROL REMOTO		
OUT   			PORTB, R16		; Y PUERTO 0 TIPO DE FUENTE
IN				R18, PINB
CPI				R18, 0x0F
BRLO			REMOTO2		; SI ES MENOR VA A REMOTO2, CABLE MAL CONESTADO
RJMP			CARGATEXTO1
REMOTO2:
	LDI				R16, 128			; 1ª LINEA DE PANTALLA
	RCALL			ENVINT				; Y ENVIA EN MANSAJE A PANTALLA 1º INFORMACION DE LINEA Y....
	LDI				YH,HIGH (E_REMOTO) 	; TEXTO A ENVIAR A PANTALLA " EQUIPO REMOTO "
	LDI				YL, LOW (E_REMOTO) 	; TEXTO A ENVIAR A PANTALLA
	LDI				R17, 16				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			;  EL TEXTO 16 CARACTERES
	RCALL			RELOJ
	RCALL			LEDPANT
;	LDS  			R19, minu			; CARGA LOS MINUTOS 
;	CPI				R19,01				; PARA ACTIVAR LA MEDICION DEL PH VARIAS VECES EN EL PRIMER MINUTO
;	BRBS			0, REMOTO2			
;	CPI				R19, 100			; COMPARA CON 100 PARA NO ENCENDER LA FUENTE Y PODER INVERTIR LA POLARIDAD
;	BRBC			0, REMOTO2			; SI ES MAYOR NO MIDE NI REDOS NI CLORO SALTA A REMOTO2 y para la fuente
;	RCALL			PRO4				; MEDICION CLORO LIBRE-- ES LA LINEA DE CONTROL REMOTO
	CALL			PRO_CONTROL			; CONTROL MEDIENTE CABLE PLANO COMO REMOTO
	SBIS			PORTD, 4				; AQUI VERIFICA SI ESTA EN MARCHA O PARADO
	RJMP			REMOTO2A
	LDI				R16, 192			; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2"
	LDI				YH, HIGH (E_MARCHA)	; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL, LOW  (E_MARCHA)	; direccion BAJA DEL TEXTO EN RAM  " EN MARCHA "    	
	RJMP			REMOTO2B
REMOTO2A:
	LDI				R16, 192			; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT				; RUTINA PARA ENVIAR A LA PANTALLA UNA INSTRUCION, " ESCRIBIR LINEA 2"
	LDI				YH, HIGH (E_PROD)	; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL, LOW  (E_PROD)	; direccion BAJA DEL TEXTO EN RAM  " SIN PRODUCCION "    	
REMOTO2B:
 	LDI				R17,16   			; bytes a enviar 
	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO E PANTALLA
	RJMP			REMOTO2				; SALTA A REMORO2
							


PRO: ; PROGRAMA PRINCIPAL MASTER
	SET
	BLD				VAL_LED, 3			; COPIA T DE SREG EN REGISTRO 2 DE LOS LED ES INTERMITENTE
	RCALL			LEDPANT
	WDR
	SBRS			CONTROL_1, 0		; SALTA LA PROXIMA INSTRUCION SI ES UNO,
	RJMP			PRO
				; RUTINA PERIFERICO DE SALIDA PCF 8574 DATO EN R17
	CLT									; PONE A CERO EL BIT T DE SREG
	BLD				VAL_LED, 3			; COPIA T DE SREG EN REGISTRO 2 DE LOS LED ES INTERMITENTE
	BLD				CONTROL_1, 0		; PASA EL REGISTRO T A CONTROL_1
	RCALL			LEDPANT
	RCALL			TECLADO				; LEER TECLADO
; MOSTRAR SAL A AÑADIR 
	SBRS			LEC_REL, 1
	RJMP			PRO_1		
	SBRC			CONTROL_1, 5		; PARA MOSTRAR LA CANTIDAD DE SAL A AÑADIR
	RJMP			PRO_1				; SALTA Y CONTINUA EL PROGRAMA
	CALL			PRO3CA3				; MUESTRA LA SAL NECESARIA		
	CALL			LINEA3
	RJMP			PROA4				; CONTINUA EL PROGRAMA
PRO_1:
;CALL 	PANTALLA2_B
;SBRS	LEC_REL, 1
;CALL 	REMOTO_3
;SBRC	LEC_REL, 1
;CALL	REMOTO_1
;MOV 	R17, LEC_REL
RCALL	PCF_C
; ENVIO DE DATOS A PANEL

;	LDS				R24, MINU
;	RCALL 			PANEL
; FRECUENCIA MEDICION DE PH
	CALL			LINEA3
 	RCALL			PRO2				; ESTA RUTINA PARA MEDIR Y CONTROLAR EL PH
 	SBRS			CONTROL, 4			; COMPRUEBA QUE TIENE SONDA DE PH
	RJMP			PROA3
	RCALL			LINEA1				; CON SONDA DE PH LINEA 1
	RCALL			LINEA2				; CON SONDA DE PH LINEA 2
	RJMP			PROA4			
PROA3:		; PANTALLA SIN SONDA DE PH
	RCALL			LINEA2PH			; Mostrar linea 2 solo concentracion de sal
	RCALL			LINEA1PH			; Mostrar linea 1 solo % de produccion
; FRECUENCIA MEDICION DE TEMPERATURA y SAL SOLO CON FUENTE ENCENDIDA

PROA4:
	SBIS			PIND, 4				; SI LA FUENTE ESTA APAGADA SALTA A
	RJMP			PROA				; PROA PARA NO MEDIR LA SAL
	CPI				LEC_REL, 3			; NO MIDE SI LOS SEGUNDOS SON MENOS DE 3
	BRLO			PROA
	RCALL			PRO3				; RUTINA MEDICION DE SAL
	CALL			REJILLA				; CALCULO VIDA DE LA REJILLA
; MEDICCION DE LA TEMPERATURA
	LDI				R19, 0				; DIRECIONAMIENTO DEL PERIFERICO
	LDI				R18, 2				; LINEA A LEER
	LDI				R26, 100			; NUMERO DE LECTURAS
	CALL			PCF_B				; RUTINA LECTURA DEL SEGUNDO CHIP

PROA4A:
	STS				RAM_TEMP, R24		; GUARDA LA LECTURA EN LA MEMORIA RAM
	CALL			PCF2_T				; RUTINA QUE PREPARA LA PRESENTACION DE LA TEMPERATURA
	NOP

PROA:  
	RCALL			RELOJ
	RCALL			TECLADO
	WDR
	NOP


; PARA MEDIR EL CLORO O REDOX
	WDR
	LDS  			R19, minu			; CARGA LOS MINUTOS 
	CPI				R19, 100			; COMPARA CON 100 PARA NO ENCENDER LA FUENTE Y PODER INVERTIR LA POLARIDAD
	BRBC			0, PRO1B			; SI ES MAYOR NO MIDE NI REDOS NI CLORO SALTA A PRO1B y para la fuente
	CPI				R19, 1				; NO ENCIENDE LS FUENTE
	BRBS			0, PRO1A
	SBRS			CONTROL_1, 2		; SALTA LA PROXIMA INSTRUCION SI ES UNO MIDE CLORO Y REDOX, OPCION NORMAL
	RJMP			PRO1A				; APAGA EL CIRCUITO DE APOYO Y NO MIDE MAS
	RCALL			PRO4				; MEDICION CLORO LIBRE
	SBRC			CONTROL, 7 			; COMPRUEBA SI TIENE SONDA DE CLORO LIBRE
	RJMP			PRO1A				; SI TIENE SALTA A PRO1A
	RCALL			PRO5				; MEDICION REDOX
	WDR
PRO1A:
	RJMP			PRO					; COMIENZA EL CICLO DEL PROGRAMA PRINCIPAL	

PRO1B: ; RUTINA PARA CUANDO EL TIEMPO ES SUPERIOR A 100	 APAGA LA FUENTE  
	RCALL			TECLADO				; LEER TACLADO	
	CALL			APAGAR_FUENTE
	RJMP			PRO
;+++++++++ TERMINA PROGRAMA PRINCIPAL +++++++++++++++++

;*** RUTINA PARA CONTROLAR LOS LED DE LA PANTALLA Y LA LUZ
LEDPANT:
	OUT				PORTA, val_led		; r15 registro control led pantalla
	CBI				PORTC, led_pant		; pone a 0 el bit de grabacion del 74lh374 
	NOP
	NOP
	SBI				PORTC, led_pant		; pone a 1 , graba el valor de portA en el 74LH374, enciende los led
	NOP
	NOP
	RET

;*** RUTINA PARA ENVIAR TEXTO A PANTALLA EN R17 NUMERO DE LETRAS
;    EN Y LA POSICION EN MEMORIA RAM ( YH, YL )	PRECISA RUTINA ENVIARBYTE
ENVIARTEXTO: 
	LD				r16, Y+      		; carga byte en r0 e incrementa Y
	RCALL			ENVIARBYTE  		; lo enviamos 
	DEC				r17 				; descuenta uno
	BRNE			ENVIARTEXTO   		; si quedan mas seguimos enviando 
	RET


;***********RETARDO DE 22 uS*********** 
; el retardo es : 195uS de retardo para r25=250 y 4Mhz de frecuencia
;  PARA 4MZ SOLO UNA INSTRUCION NOP PARA 8MZ 6 INSTRUCIONES NOP

RETARDO:
	WDR
	NOP
	DEC				R25 
	BRNE			RETARDO   		;
	RET

; RUTINA PARA CARGAR LOS VALORES PROGRAMADOS EN EEPROM A RAM
; CARGA EL PH


LINEA1: ;RUTINA ESCRITURA LINEA1 
	LDI				R16, 80				; PONE UNA P
	STS				$070, R16	
	LDI				R16, 114			; PONE UNA r
	STS				$071, R16	
	LDI				R16, 111			; PONE UNA o
	STS				$072, R16	
	LDI				R16, 100			; PONE UNA d
	STS				$073, R16
	LDI				R16, 32				; PONE UN ESPACIO
	STS				$074, R16			
	STS				$079, R16
	STS				$07C, R16
	STS				$07D, R16
	STS				$07E, R16
	STS				$07F, R16
	LDI				R16, 65				; PONE UNA A
	STS				$075, R16
	LDI				R16, 117			; PONE UNA u
	STS				$076, R16
	LDI				R16, 116			; PONE UNA t
	STS				$077, R16
	LDI				R16, 111			; PONE UNA O
	STS				$078, R16
	LDI				R16, 46				; PONE EL PUNTO DEL PH
	STS				$07E, R16
	LDI				R16, 45
	STS				$07D, R16
	STS				$07F, R16	
	SBRC			CONTROL, 7 			; COMPRUEBA SI TIENE SONDA DE CLORO LIBRE
	RJMP			LINEA1A
	SBRC			CONTROL, 6			; COMPRUEBA SI TIENE SONDA DE REDOX
	RJMP			LINEA1A
	LDS				R24, RAMP_PRO
;	SBRC			CONTROL_1, 3
;	LDS				R24, RAM_PRO_PRO_M	; SOLO EN CASO DE ACTUAR EL PORCENTAJE DE PRODUCION
	SBRC			CONTROL, 3			; SALTA LA PROXIMA INSTRUCION SI ES CERO, SUPERCLORACION
	LDI				R24, 100			; SOLO EN CASO DE SUPERCLORACION
	RCALL			RADC				; RUTINA PARA CONVERTIR EN ANALOGICO
	STS				$075, R1
	STS				$076, R2
	STS				$077, R3
	LDI				R16, 37				; PONE UN %
	STS				$078, R16
LINEA1A:
	LDI				R16, 80				; PONE UNA P
	STS				$07A, R16			; EN LA MEMORIA RAM DEL MICRO
	LDI				R16, 104			; PONE UNA h
	STS				$07B, R16		; EN LA MEMORIA RAM DEL MICRO	
; NO ESCRIBE EL PH LOS PRIMEROS DOS MINUTOS
	LDS				R19, NCICLOS
	CPI				R19, 00				; VERIFICA QUE A PASADO UN MINUTO PARA ENCENDER LA FUENTE
	BRBS			0, LINEA1_A			; SI ES MENOR DE DOS MINUTOS SALTA A VOLVER

	LDS				R19, MINU
	CPI				R19, 02				; VERIFICA QUE A PASADO UN MINUTO PARA ENCENDER LA FUENTE
	BRBS			0, LINEA1_A			; SI ES MENOR DE DOS MINUTOS SALTA A VOLVER

	LDS				R24, RAM_PH			; LEE EL PH DE LA RAM
	RCALL			RADC				; RUTINA PARA CONVERTIR EN ANALOGICO
	STS				$07C, R1
	STS				$07D, R2			; RESULTADO DE DECENAS
	STS				$07F, R3			; RESULTADO UNIDADES			
	LDS				R24, RAM_PH
	CPI				R24, 120			; VALOR MAX DEL PH SOLO DOS CIFRAS
	BRBS			0, LINEA1_A			; SI ES MAYOR NO SALTA Y PONE E.E
	LDI 			R16, 32
	STS				$07C, R16			; PONE UN ESPACIO 
	LDI				R16, 69				; PONE E
	STS				$07D, R16
	STS				$07F, R16
	LDI				R16, 46				; PONE .
	STS				$07E, R16

LINEA1_A:
	LDI				R16, 128			; ESCRIBIR LINEA 1 valor 128
	RCALL			ENVINT				; En subrrutina Env_doi Envia instrucion para escribir en linea 1
	LDI				YH, HIGH (LIN1)		; POSICION BIT ALTO DEL TEXTO A ENVIAR ram en 070
	LDI				YL, LOW  (LIN1)		; POSICION BIT BAJO DEL TEXTO A ENVIAR
	LDI				R17,16				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			; RUTINA EN ESTE FICHERO PRECISA SUBRRUTINA ENV_DOI	
	RET	


.INCLUDE "NO_TECLA.ASM"

NIVEL_DEPOSITO:
	LDI				R16, 192		; ESCRIBIR EN LINEA 2
	RCALL			ENVINT				; Y ENVIA EN MANSAJE A PANTALLA 1º INFORMACION DE LINEA Y....
	LDI				YH,HIGH (N_DEPOSITO) ;TEXTO A ENVIAR A PANTALLA "NIVEL DEPOSITO"
	LDI				YL, LOW (N_DEPOSITO) ;TEXTO A ENVIAR A PANTALLA
	LDI				R17, 16				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			; 2º EL TEXTO 16 CARACTERES
	RET

LINEA2: ; RUTINA ESCRITURA LINEA2
	SBRS			VAL_LED, 5			; VERIFICA EL LED 5 FALTA DE NIVEL EN EL DEPOSITO
	RJMP			LINEA10				; Y SALTA ESTA INSTRUCION SI ES UNO "HAY NIVEL"
	SBRS			LEC_REL, 1
	RJMP			NIVEL_DEPOSITO		; VA CADA 3 SEGUNDOS AL MENSAJE DE "NIVEL DEPOSITO"

LINEA10:

	LDI				R16, 83				; PONE UNA S
	STS				$090, R16
	LDI				R16, 97				; PONE UNA a
	STS				$091, R16	
	LDI				R16, 108			; PONE UNA l
	STS				$092, R16	
	LDI				R16, 46				; PONE UN .
	STS				$096, R16	
	STS				$09E, R16
	LDI				R16, 32				; CODIGO DEL ESPACIO			
	STS				$093, R16
	STS				$094, R16
	STS				$098, R16
	STS				$09C, R16
	LDS				R24, RAM_SAL_C		; CARGA DE LA RAM EL VALOR DE LA MEDICION DE LA SAL
CPI				R24, 99
BRBC			0, LINEA10_A

	CPI				R24, 61
	BRLO			LINEA10_1
	LDI				R24, 60				; SI ES MAYOR DE 60 PONE > Y DA VALOR DE 60 A SAL
	LDI				R16, 62
	STS				$093, R16			
LINEA10_1:
;	SUBI			R24, 0				; RESTA UNA CANTIDAD COMO CONTENIDO DE CAL EN EL AGUA
	NOP
	RCALL			RADC
	STS				$094, R1
	STS				$095, R2			; VALOR DE LAS DECENAS
	STS				$097, R3			; VALOR DE LAS UNIDADES
RJMP			LINEA10_B
LINEA10_A:
LDI	R16, 45			; PONE UN -
STS				$095, R16
STS				$097, R16
LINEA10_B:
	LDI				R16, 80				; PONE UNA P 
	STS				$099, R16
	LDI				R16, 104			; PONE UNA H
	STS				$09A, R16
	LDI				R16, 80 			; PONE UNA P
	STS				$09B, R16	
	SBRS			CONTROL, 7 			; COMPRUEBA SI TIENE SONDA DE CLORO LIBRE
	RJMP			LINEA2A				; SI NO TIENE SALTA A LINEA2A
	LDS				R24, RAM_CL
	RCALL			RADC
	LDI				R16, 32				; PONE UN ESPACIO PARA ELIMINAR LA P
	STS				$099, R16
	LDI				R16, 67				; ESCRIBE UN C
	STS				$09A, R16
	LDI				R16, 108 			; PONE UNA l
	STS				$09B, R16	
	STS				$09D, R2
	STS				$09F, R3			
	RJMP			LINEA2B
LINEA2A: 		; CON SONDA DE REDOX
	SBRS			CONTROL, 6			; COMPRUEBA SI TIENE SONDA DE REDOX
	RJMP			LINEA2C				; SI NO TIENE SALTA A LINEA 3A
	LDS				R24, RAM_RD
	RCALL			RADC5I				; RUTINA ESPECIAL PARA CONVERTIR EL REDOX EN BCD
	LDI				R16, 32				; PONE UN ESPACIO PARA ELIMINAR LA P
	STS				$099, R16
	LDI				R16, 82				; PONE UNA R
	STS				$09A, R16
	LDI				R16, 100			; PONE UNA d
	STS				$09B, R16
	STS				$09D, R1
	STS				$09E, R2	
	STS				$09F, R3		
	RJMP			LINEA2B
LINEA2C:	
	LDS				R24, RAMP_PH
	RCALL			RADC	
	STS				$09C, R1
	STS				$09D, R2
	STS				$09F, R3			
;	RJMP			LINEA2B
;	LDI				R16, 45				; PONE UNA -
;	MOV				R3, R16
;	MOV				R2, R16				; PONE UNA -
;	STS				$09D, R2	
;	STS				$09F, R3		

LINEA2B:
	LDI				R16, 192			; 11000000 escribir en linea 2 linea (192)( linea 4 seria 212)
	RCALL			ENVINT
	LDI				YH, HIGH (LIN2)		; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL, LOW  (LIN2)		; direccion BAJA DEL TEXTO EN RAM      	
  	LDI				R17,16 				; bytes a enviar 
	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO A PANTALLA
	RET
;       20x4        16x4   tipo de display
; linea 1-128 		128 
; linea 2-192		192
; linea 3-148		144
; linea 4-212		208
;LINEA3:		
LINEA3:
	LDI				R16, 144		; ESCRIBIR LINEA 3 - 144
	RCALL			ENVINT				; En subrrutina Env_doi Envia instrucion para escribir en linea 1
	LDI				YH, HIGH (PRUEBA)	; POSICION BIT ALTO DEL TEXTO A ENVIAR ram en 070
	LDI				YL, LOW  (PRUEBA)	; POSICION BIT BAJO DEL TEXTO A ENVIAR
	LDI				R17,16				; NUMERO DE DIGITOS A ENVIAR A PANTALLA
	RCALL			ENVIARTEXTO			; RUTINA EN ESTE FICHERO PRECISA SUBRRUTINA ENV_DOI
;	RET

LINEA4:

	MOV				R24, LEC_REL
	RCALL			RADC
	STS				$247, R1
	STS				$248, R2
	STS				$249, R3
	LDS				R24, MINU
	RCALL			RADC
	STS				$24B, R1
	STS				$24C, R2
	STS				$24D, R3	
	LDS				R24, NCICLOS
	RCALL			RADC
;	STS				$24E, R2
	STS				$24F, R3
	LDI				R16, 208			; 11000000 escribir en linea 4 linea (192)( linea 4 seria 212)
	RCALL			ENVINT
	LDI				YH, HIGH (PRUEBA_1)	; POSICION ALTA DEL TAXTO EN RAM 080
	LDI				YL, LOW  (PRUEBA_1)	; direccion BAJA DEL TEXTO EN RAM      	
  	LDI				R17,16   			; bytes a enviar 
	RCALL			ENVIARTEXTO			; RUTINA PARA ENVIAR TEXTO E PANRALLA

	RET







CALL ENCENDER_GRA	; ENCIENDE LA PANTALLA GRAFICA

LDI R27, 0			; POSICION X LINEA 0 A 8
;LDI	R26, 3			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (LIN1P)
LDI	YL, LOW (LIN1P)
CALL PRO_GRA_1		

LDI R27, 1			; POSICION X LINEA 0 A 8
;LDI	R26, 3			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (LIN2P)
LDI	YL, LOW (LIN2P)
CALL PRO_GRA_1		

LDI R27, 2			; POSICION X LINEA 0 A 8
;LDI	R26, 3			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (LIN1)
LDI	YL, LOW (LIN1)
CALL PRO_GRA_1		

LDI R27, 3			; POSICION X LINEA 0 A 8
;LDI	R26, 4			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (LIN2)
LDI	YL, LOW (LIN2)
CALL PRO_GRA_1		


LDI R27, 4			; POSICION X LINEA 0 A 8
;LDI	R26, 3			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (PRUEBA)
LDI	YL, LOW (PRUEBA)
CALL PRO_GRA_1		

LDI R27, 5			; POSICION X LINEA 0 A 8
;LDI	R26, 4			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (PRUEBA_1)
LDI	YL, LOW (PRUEBA_1)
CALL PRO_GRA_1		

LDI R27, 6			; POSICION X LINEA 0 A 8
;LDI	R26, 4			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (L_BLANCA)
LDI	YL, LOW (L_BLANCA)
CALL PRO_GRA_1		

LDI R27, 7			; POSICION X LINEA 0 A 8
;LDI	R26, 4			; POSICION Y DE 0 A 16
LDI	R24, 16		; NUMERO DE CARACTERES A ESCRIBIR
LDI	YH, HIGH (L_BLANCA)
LDI	YL, LOW (L_BLANCA)
CALL PRO_GRA_1		

RET

ENVIARTEXTO_2: 
	LD				r16, Y+      		; carga byte en r0 e incrementa Y
	RCALL			ENVIARBYTE_2  		; lo enviamos 
	DEC				r17 				; descuenta uno
	BRNE			ENVIARTEXTO_2  		; si quedan mas seguimos enviando 
	RET


;.INCLUDE "SAA1064.ASM"
.INCLUDE "COMPARA2.ASM"
.INCLUDE "PRO_RD.ASM"
.INCLUDE "PRO_CL.ASM"	
.INCLUDE "PRO_PRO.ASM"
.INCLUDE "MED_PH+.ASM"
.INCLUDE "MED_SAL.ASM"
.INCLUDE "MED_CL.ASM"
.INCLUDE "MED_RD.ASM"
.INCLUDE "AJUSTE_CL.ASM"
.INCLUDE "I2C_ATMEGA16.ASM"
.INCLUDE "I2C_ATMEGA16_B.ASM"
.INCLUDE "I2C_ATMEGA16_C.ASM"
.INCLUDE "DATOS.ASM"
.INCLUDE "PRO_CICLOS.ASM"
.INCLUDE "RETARDO240.ASM"
;.INCLUDE "RADIO.ASM"
.INCLUDE "PANEL_A.ASM"
.INCLUDE "TEXTO_LCD2.ASM"
;.CSEG 
;.ORG 0x0E90; 
;.INCLUDE "FRECUENCIMETRO.ASM"
;.INCLUDE "PI2C.ASM"				; esta opcion es con i2c del propio micro atmega16
;.CSEG 
;.ORG 0x0F20;    
.INCLUDE "AJUSTE_PRODUCION.ASM"
.INCLUDE "MULTIPLICAR.ASM"
.INCLUDE "UART.ASM"
.INCLUDE "RRADIO.ASM"
.INCLUDE "INI_ATMEGA16.ASM"						; PARAMETROS DE INICIALIZACION DEL MICRO
.INCLUDE "HORAS.ASM"
.INCLUDE "AYUDA_RD_CL.ASM"
.INCLUDE "VIDA_REJILLA.ASM"
.INCLUDE "CONTROL_CAUDAL.ASM"
.INCLUDE "REMOTO_CONTROL.ASM"

;*************TEXTO*************** 

.CSEG 
.ORG 0x1300;       
                        
TEXTO:		.DB "Rd000 S00 M00 C0"
			.DB "     -.- PHR 7.4"
TEXTO1:		.DB "PRODUCION %     " 
			.DB "EQUIPO DETENIDO "
			.DB "  -.-  Kgr/M3   "
;			           A  Ñ  A  D  I  R        S  A  L
			.DB "  A",00,"ADIR  SAL   "
;			.DB 32,32,65,00,65,68,73,82,32,32,83,65,76,32,32,32
			.DB "   A J U S T E  "
			.DB "  SIN  CAUDAL   "
			.DB " EQUIPO REMOTO  "
			.DB "   EN  MARCHA   "
			.DB " SIN PRODUCCION "
			.DB " NIVEL DEPOSITO "
			.DB "TEMPERATURA   . "
TEXTO2:
			.DB "   EN ESPERA    "
			.DB "      SEGUNDOS  "
			.DB "CONSULTAR MANUAL"
			.DB "  A V E R I A   "
			.DB "FALLO PRUDUCCION"
			.DB " Sust. Sonda Ph "
			.DB " ERROR CONEXION "
			.DB "                "
.CSEG 
.ORG 0x1400

TEXTO3:
			.DB " Modelo Serie L "
			.DB " Modelo  L - 50 "
			.DB " Modelo  L - 80 "
			.DB " Modelo  L -120 "
			.DB " Modelo  L -180 "
			.DB " Modelo  L -220 "
			.DB " Modelo  L - 30 "
			.DB " Modelo  I -300 "
			.DB " Modelo  I -350 "
			.DB " Modelo  I -400 "
			.DB " Modelo  I -450 "
			.DB " Modelo  I -500 "
			.DB " Modelo  I -550 "
			.DB " Modelo  I -650 "
			.DB " Modelo  I -800 "						
			.DB " Modelo  I-1200 "

;.CSEG 
;.ORG 0x0F80 
TEXTO4:
			.DB "                "
			.DB "   TEAP.S.L.    "
			.DB "  eli - Tpools  "
			.DB "WWW.COINPOL.COM "
			.DB "AQUACASAR, S.L. " 
			.DB "NUEVO CLIENTE 1 "
			.DB "NUEVO CLIENTE 2 "
			.DB "NUEVO CLIENTE 3 "
			.DB "NUEVO CLIENTE 4 "
			.DB "NUEVO CLIENTE 5 "
			.DB "NUEVO CLIENTE 6 "
			.DB "NUEVO CLIENTE 7 "
			.DB "NUEVO CLIENTE 8 "

TEXTO5:
			.DB "    EN ESPERA   "
			.DB "      SEGUNDOS  "

.CSEG 
.ORG 0x1500
TEXTO6:
			.DB "                    "
			.DB "                    "
			.DB "                    "
			.DB "                    "
			.DB "                    "
			.DB "TEMPERATURA --.- ",223,"C " ; LA Ñ ES 238
			.DB "PRO.TOTAL ---Gr/Cl/H"
			.DB "VALORES PROGRAMADOS "
			.DB "Ph -.- Rd --- Cl -.-"
TEXTO7:  ; SE PRESENTA AL PULSAR SALIR

			.DB "  Prod. por celda   "
			.DB "1-20 2-21 3-21 4-19 "
			.DB " Tension por celda  "
			.DB " 5.1  5.3  5.2  5.3 "


;.CSEG 
.;ORG 0x1118


.INCLUDE "PRO_RD_CL.ASM"
.INCLUDE "RETARDO.ASM"
.INCLUDE "VER_ERROR.ASM"
.INCLUDE "MED_INI_SAL.ASM"
.INCLUDE "PANTALLA2.ASM"
.INCLUDE "P_GRAFICO.ASM"
.INCLUDE "TEXTO_LCD.ASM"
;.INCLUDE "CONTROL_REMOTO.ASM"
;****HASTA AQUÍ EL PROGRAMA******* 


