;                       AJUSTE_PARAMETROS
; EN R21 SE GUARDAN LOS RESULTADOS 
; BIT 0 PARA ACTIVAR O NO LA FUENTE, SI EL CONTENIDO DE CLORO Ó REDOX ES ALTO PARAR 
; TAMBIEN ACTUA SOBRE EL BIT 0 EL FACTOR DE PRODUCION
; BIT 1 PARA EL PH Y ACTIVAR Ó NO LA BOMBA
; AQUI SE LEEN LOS VALORES DE PH, REDOX, CLORO LIBRE, Y ES POSIBLE LEER LA TEMPERATURA DEL AGUA
; ESTA RUTINA SE EJECUTA CADA 10 MINUTOS ESTE VALOR SE ALMACENA EN R9 Y SE CONTROLA EN LA RUTINA RELOJ 
; R6 REGISTRO DE CONTROL


AJUSTE_PARAMETROS:

;	LDI			R24,20		; TIEMPO PARA EL FRECUENCIMETRO
	RCALL		FREC0		; LLAMADA A LA RUTINA RESULTADO EN R4 Y R5



	RET